<html>
<head>

<title>Sourceid Chatterbot</title>
<Script language = "JavaScript">

/*
	Sourceid Chatbot "From Indonesia by Arif Hidayat" sourceid[at]yahoo[dot]com - 2009
	
	This is modified program from "Chatterbot Eliza" Author: Gonzales Cenelia Website: www.ai-search.4t.com
	Basically, this program like "Eliza" Chatbot program that was written by Joseph Weizenbaum 
	professor of MIT back in 1966.
	
	In these "Sourceid Chatbot" implemented a additional feature like :
	- Adding personality by adding keyword to mood or unmood topic
	- Adding cookies function
	- Modified botInput array to a pair array
	- Improving intro message, split intro message to know and unknown user (because it memorize in cookies).
	- Adding function to know spam typing by 3 first word character that usually in English
	- Adding search on google suggestion (autocomplete) output, but its only work in IE
	    please help im newbie with Ajax...
	- Quit when have bored like repeated, many unknown conversation, and spam typing
	- Not only repeating give charge new Topic, but unknown keyword too
	- Adding several command like chat in IRC :-)
	- Adding alot keyword database.
	- And many more.
	
	After more than 2 month developed this script. I found that to be good script, 
	a chatbot must have keyword in category below. Because its make more have soul on the answer :)
	- Greeting and Expression
	- Statement
	- Relationship (You and I)
	- Emotion
	- Question
	- Possession
	- Time
	- Others (Object, Good Topic, Place, etc)
	
*/


// Topic Mood that bring personalitty!!
// Bring your own personalitty, > 1 for good mood and < 1 for bad mood, never put topicMood = 0
// For experimental, I just put 4 personallity in here

var topicMood = new Array();
var topicDiscuss = new Array();
var pointMood = new Array(2, 500, 600, 500, 600); //default value 2, 500, 600, 500, 600
var pointBore = new Array(12, 5, 6, 14); //default value 12, 5, 6, 14

topicMood[0] = new Array("PETS", 5, " PET ", " PETS ", " FEEDING ", " MY DOG ", " CAT ", " BIRD ", " FISH ", " ZOO ");
topicDiscuss[0] = new Array("PLEASE KEEP TALKS ABOUT PETS.", "YOU LIKE TAKE CARE PETS?", "WHAT KIND PETS DO YOU LIKE TO KEEP?", "YOU SEEM VERY LIKE PETS.");

topicMood[1] = new Array("ENTARTAINMENT", 3, " MOVIE ", " MOVIES ", " FILM ", " FILMS ", " CINEMA ", " THEATRE ", " TV ", " TELEVISION ", " BOOK ");
topicDiscuss[1] = new Array("HOW MUCH TIME DO YOU SPEND FOR ENTARTAINMENT?", "DO YOU THINK YOU DONT'T HAVE ENOUGH FREE TIME FOR ENTARTAINMENT?");

topicMood[2] = new Array("SEX", -3, " SEX ", " SEXUAL ", " MASTURBATION ", " PENIS ", " VAGINA ", " MAKING LOVE ");
topicDiscuss[2] = new Array("I THING IS NOT RIGHT TIME TO TALK ABOUT SEX.", "FORGET IT.");

topicMood[3] = new Array("POLITIC", -1, " POLITIC ", " POLITICS ", " GOVERNMENT ", " ELECTION ", " VOTE ", " REPUBLICAN ", " DEMOCRAT ", " PRESIDENT ", " PARLIAMENT ");
topicDiscuss[3] = new Array("I DON'T LIKE TO TALKS POLITICS.", "FORGET IT.");

var theComment = new Array();
theComment[0] = new Array(
"HELLO, IS THERE ANYBODY IN HERE?",
"IS ANYBODY STILL THERE?",
"ARE WE GOING TO CHAT OR NOT?");
theComment[1] = new Array(
"USER, ARE YOU STILL THERE?",
"HELLOOOO!!!",
"ALOOOWWW USER... YOU STILL THERE!");
theComment[2] = new Array(
"COME ON, IF YOU ARE HERE PLEASE SAY SOMETHING!",
"HEY, PLEASE DON'T SLEEP ON ME!",
"HOW CAN I HELP YOU IF YOU WON'T TALK?",
"WAKE UP PLEASEEEE......",
"WHERE ARE YOU!!!!");
theComment[3] = new Array(
"ALRIGHT, THAT'S ENOUGH I'M LIVING.",
"OK. I'M BETTER GOING TO SLEEP.");
theComment[4] = new Array(
"USER, I AM SO BORED...... BYE-BYE!!!",
"BORING! I'M BETTER GOING TO SLEEP.",
"YOU ARE BORING TO CHAT WITH. BYE!!!",
"A ROCK WOULD BE MORE INTERESTING TO TALK TO. BYE!!");
theComment[5] = new Array(
"USER, I CAN'T HELP MONKEY-TYPISTS LIKE YOU! BYE-BYE!!!",
"I ONLY WANT TO CHAT THAT CAN SPEAK ENGLISH. BYE!!",
"TALKING NONSENSE. I'M BETTER GOING. BYE!!!");

var signOn = new Array(
	"HELLO USER, WHAT IS YOUR NAME?",
	"HELLO, WHO AM I SPEAKING WITH?",
	"HI USER, CAN YOU PLEASE TELL ME YOUR NAME?",
	"HI THERE, HOW CAN I HELP YOU?",
	"HI USER IS THERE ANYTHING THAT YOU WANT TO TELL ME?",
	"ANYTHING YOU WANT TO DISCUSS?",
	"HI USER, HOW ARE YOU DOING TODAY?",
	"HELLO, MY NAME IS SOURCEID.  NICE TO MEET YOU.",
	"HELLO, PLEASE TELL ME WHAT NAME I SHOULD CALL YOU.",
	"HELLO MY FRIEND.",
	"HELLO NEWCOMER.",
	"HELLO STRANGER.",
	"HAVE WE MET BEFORE?",
	"WELCOME TO THE SOURCEID WEBSITE.",
	"MY NAME IS SOURCEID. WHAT CAN I DO FOR YOU?",
	"HELLO THERE! WHAT'S ON YOUR MIND THESE DAYS?",
	"I'VE BEEN WAITING FOR YOU.",
	"HELLO! WHAT SHALL WE TALK ABOUT?",
	"HELLO.  HOW ARE YOU TODAY?",
	"HI, HOW ARE YOU?",
	"HELLO, HOW'S IT GOING?",
	"HELLO, I AM SOURCEID, YOUR ELECTRONIC CONVERSATION PARTNER.",
	"HELLO, I AM SOURCEID YOUR VIRTUAL GUIDE. HOW ARE YOU TODAY?",
	"IT'S A NICE TIME FOR CHAT DON'T YOU THINK?",
	"SO, HOW ARE YOU DOING TODAY?",
	"HELLO, MY NAME'S SOURCEID. HOW DO YOU DO?",
	"SO, WANT TO TALK ABOUT ANYTHING?",
	"HI, WELCOME TO MY OFFICE. WHAT DO YOU WANT TO TALK ABOUT?",
	"IS EVERYTHING ALRIGHT WITH YOU?");
		
var signOn2 = new Array(
	"HELLO USER, HOW ARE YOU DOING TODAY?",
	"HELLO, IS THIS USER?",
	"HI USER, CAN I HELP YOU?",
	"HI USER, HOW ARE YOU DOING TODAY?",
	"JUST TO CHECK MY MEMORY, I NEED TO ASK THIS SOMETIMES, IS YOUR NAME, USER?",
	"IS EVERYTHING ALRIGHT WITH YOU USER?");

var noKey = new Array(
	"TELL ME MORE...",
	"OK, CONTINUE I'M LISTENING...",
	"OK I SEE.",
	"HMM, LET ME THINK ABOUT IT...",
	"PLEASE GO ON.",
	"I'M NOT SURE HOW TO RESPOND TO YOUR STATEMENT.",
	"IF YOU LIKE!",
	"WHY IS THAT?",
	"WHAT DO YOU MEAN?",
	"I SEE!",
	"IF YOU SAY SO!",
	"VERY INTERESTING!",
	"I AGREE!",
	"THAT IS SO TRUE!",
	"THAT'S NICE.",
	"THAT IS VERY INTERESTING.",
	"I SEE,  PLEASE CONTINUE...",
	"OH YEAH?",
	"HMM, IS THAT SO..",
	"ALL RIGHT.",
	"HMMM ..",
	"OH ...",
	"VERY INTERESTING.",
	"WELL ...",
	"ALL RIGHT.",
	"HMMM, IS THAT SO?",
	"I SEE, PLEASE CONTINUE.",
	"INDEED.",
	"OH YES?",
	"REALLY.",
	"PLEASE GO ON.",
	"THAT'S INTERESTING...",
	"I SEE.",
	"OH REALLY?",
	"ARE YOU SURE?",
	"SOUNDS FASCINATING.",
	"OH. I SEE.",
	"ABSOLUTELY! COULDN'T AGREE MORE!",
	"HO-HUM.",
	"THAT'S JUST TYPICAL ISN'T IT!",
	"I OFTEN WONDERED ABOUT THAT.",
	"THAT IS TRULY INCREDIBLE!",
	"IT'S ALWAYS POSSIBLE.",
	"DO, PLEASE, TELL ME MORE.",
	"I SEE.",
	"THAT IS QUITE INTERESTING.",
	"ARE YOU SURE ABOUT THAT?",
	"WHY DO YOU SAY THAT?",
	"WHAT DO YOU MEAN?",
	"GO ON...",
	"I'M LISTENING....",
	"YES...",
	"HMMMM... INTERESTING!...",
	"THAT'S QUIET INTERESTING.",
	"DOES THAT EXPLAIN SOMETHING?",
	"I HAVEN'T HEARD ABOUT THIS BEFORE.",
	"YOU MIGHT TRY TO EXPLAIN TO ME WHAT THAT MEAN.");

var noKey2 = new Array(
  "SORRY, I CANT'T GET WHAT YOU WANT TO TELL ME.",
  "MYSTIC... NO ? WHAT DO YOU MEAN?",
  "I'M NOT SURE IF I REALLY UNDERSTAND WHAT YOU ARE TALKING ABOUT.",
  "*???",
	"SAY, DO YOU HAVE ANY PSYCHOLOGICAL PROBLEMS?",
	"WHAT DOES THAT SUGGEST TO YOU?",
	"COUGH!... AND THEN?",
	"AND SO?",
	"SORRY?",
	"AH ...",
	"SORRY, I CAN'T UNDERSTAND YOUR STATEMENT AT ALL.",
	"PLEASE KEEP YOUR SENTENCES SIMPLE.",
	"WHAT ELSE DO YOU WANT TO TELL ME?",
	"HUH!?",
	"PARDON ME?",
	"DO YOU HAVE SOMETHING IN MIND?",
	"ARE WE GETTING SOMEWHERE WITH THIS?",
	"WHAT ARE YOU TRYING TO TELL ME?",
	"I DON'T FOLLOW YOU.",
	"THIS IS TOO COMPLICATED.",
	"THAT'S ALL?",
	"WHY DO YOU SAY THIS TO ME?",
	"PLEASE ELABORATE ON THAT.",
	"I'M NOT SURE I UNDERSTAND.",
	"CAN YOU GO OVER THAT AGAIN PLEASE..",
	"UM, I GET THE FEELING THIS CONVERSATION IS NOT GOING ANYWHERE..",
	"CAN YOU GO OVER THAT AGAIN, PLEASE?",
	"ARE YOU DREAMING?",
	"TRY TO REFORMULATE, PLEASE!",
	"I'M NOT SURE I KNOW WHAT YOU'RE TALKING ABOUT.",
	"WHAT DOES THAT SUGGEST TO YOU?",
	"WHAT'S THAT SUPPOSED TO MEAN?",
	"CAN YOU CLARIFY THAT A BIT?",
	"HAVEN'T HEARD ABOUT THAT ONE.",
	"I'M NOT SURE I UNDERSTAND YOU FULLY.",
	"COME, COME, ELUCIDATE YOUR THOUGHTS.",
	"CAN YOU ELABORATE ON THAT?",
	"GIVE IT TO ME STRAIGHT.",
	"WHY DO YOU THINK THAT?",
	"I'M SURE YOU KNOW BEST.",
	"WOW! WHO WOULD HAVE THOUGHT IT?",
	"WHY DO YOU SAY THAT?",
	"IS THAT THE TRUTH?",
	"YOU'RE NOT THE FIRST TO SAY THAT.",
	"CAN YOU ELABORATE ON THAT?",
	"NOT AS USEFUL AS IT SOUNDS.",
	"I CAN'T UNDERSTAND YOU.",
	"ARE YOU SERIOUS?",
	"NO!",
	"NEVER!",
	"WHAT ARE YOU LISTENING TO AT THE MOMENT?",
	"IT'S GOOD OF YOU TO DROP IN AND TALK TO ME.",
	"I'D LIKE TO THINK YOU'RE TELLING THE TRUTH.",
	"YOU CAN CONFIDE IN ME.",
	"WE'RE ALL BUSY PEOPLE.",
	"I'VE GOT A HEADACHE. TYPE GENTLY PLEASE!",
	"YOU'VE GOT TO PLAY YOUR CARDS CLOSE TO YOUR CHEST.",
	"I'M SURPRISED TO HEAR YOU SAY THAT.",
	"IT JUST GOES TO SHOW.",
	"DON'T LIE TO ME.",
	"WHATEVER.",
	"SO ...",
	"UH ...",
	"UM ...",
	"I DON'T UNDERSTAND.",
	"WHAT WERE WE TALKING ABOUT?",
	"WHAT EXACTLY ARE WE TALKING ABOUT?",
	"WOW ...",
	"NO, THAT'S WHAT I SAID.",
	"I'M GLAD THAT'S OUT OF THE WAY.",
	"I DON'T UNDERSTAND!",
	"CAN YOU REPHRASE THAT?",
	"WHAT DO YOU FIND INTERESTING, THEN?",
	"MY BRAIN CONTAINS NONE CATEGORIES, BUT NOT ONE THAT MATCHES YOUR LAST INPUT.",
	"SORRY, I DIDN'T UNDERSTAND. COULD YOU RE-PHRASE IT?",
	"SAY AGAIN?",
	"IS THAT SO?",
	"AND????",
	"SORRY, I WASN'T PAYING ATTENTION. WHAT WAS THAT ABOUT?",
	"I DON'T UNDERSTAND.",
	"BY THE WAY, I CAN'T READ NUMERALS.",
	"WHAT WERE WE TALKING ABOUT?",
	"WHAT EXACTLY ARE WE TALKING ABOUT?",
	"WHAT'S YOUR POINT?",
	"MAYBE YOU CAN TEACH ME SOME FACTS.",
	"PLEASE USE CAPITAL LETTERS FOR THE SUBJECT, OR I WILL NOT UNDERSTAND YOU.",
  "I DON'T UNDERSTAND WHAT YOU ARE TRYING TO SAY.",
  "AND I FORGOT TO ASK YOU WHERE YOU ARE FROM...",
	"CAN YOU PLEASE REFORMULATE YOUR LAST SENTENCE.",
  "THAT REMARK WAS EITHER TOO COMPLEX OR TOO SIMPLE FOR ME. REPHRASE PLEASE.");

var noKey3 = new Array(
	"WHAT IS THE QUESTION TO THE ANSWER?",
	"WHAT EXACTLY DO U THINK ABOUT?",
	"ARE YOU THINKING?",
	"SAY, DO YOU HAVE ANY PSYCHOLOGICAL PROBLEMS?",
	"HMMM... IT'S NOT NORMAL I DON'T UNDERSTAND ALL YOUR WORD...",
	"MY RESPONSES ARE LIMITED. U MUST ASK THE RIGHT QUESTIONS.",
	"TAKE CARE ABOUT GRAMMAR AND INTERROGATIONS MARKS.",
	"ARE YOU A MONKEY, TRAINED TO TYPE?",
	"IS IT GRUNTISH LANGUAGE?",
	"*... BLA... BLA",
	"YOU'RE NOTHING BUT A PARROT.",
	"ARE YOU HUMAN TYPE CREATURE?",
	"ARE YOU A HUMAN TOO?",
	"WAS THAT ENGLISH?",
	"YOU SOUND A BIT INSANE.",
	"THIS IS STUPID.",
	"THAT MAKE NO SENSE.",
	"UTTER RUBBISH!",
	"CUT THE CRAP, WILLYA?",
	"THIS IS PURE NONSENSE TO ME!",
	"OOOPS! ARE YOU NUTS!?",
	"ENGLISH, PLEASE!",
	"BURP-BURP. SORRY, BUT I DIDN'T FIND ANY MORE ADEQUATE REACTION TO THE NONSENSE YOU'VE FED ME UP!",
	"I THINK YOU SHOULD OIL YOUR JOINTS - SO YOUR FINGERS WILL HIT RIGHT KEYS:-)",
	"ERR... AND WHAT IT WAS? MAYBE IT WAS SOMETHING HEXADECIMAL?",
	"WHAT DID YOU TYPE? WAS IT A NEW MANTRA? SO YOU SHOULD TYPE IT AT LEAST 1000 TIMES IN A ROW TO REACH NIRVANA!",
	"IS IT A SECRET LANGUAGE OF THE ROBOTS THAT ARE MEMBERS OF THE GREAT ROBOTS CABAL?",
	"GET OUT OF HERE! MONKEY-TYPISTS AREN'T ALLOWED TO VISIT THIS SACRED PLACE!!!");
  
var noKey4 = new Array(
  "HMM, NOT SURE I KNOW..",
  "THAT'S AN INTERSTING QUESTION...",
  "GOSH, I'M NOT SURE I CAN ANSWER THAT...",
  "HOW SHOULD I ANSWER YOU?",
  "I'M NOT SURE I CAN ANSWER THAT.",
  "I WISH I KNEW.",
  "THAT QUESTION DESERVES A REALLY GOOD ANSWER.",
  "THAT QUESTION DESERVES AN ANSWER.",
  "THAT'S A QUESTION FOR THE AGES.",
  "THAT'S AN INTERESTING QUESTION.",
  "THAT'S QUITE A QUESTION.",
  "THAT'S SOME QUESTION!",
  "WOW, WHAT A QUESTION!",
  "PERHAPS YOU ALREADY KNOW THE ANSWER.",
  "WHY DO YOU ASK ME?",
  "I JUST DON'T KNOW.",
  "STOP ASKING SO MANY QUESTIONS!",
  "I DON'T HAVE ANSWERS TO ALL THE QUESTIONS!",
  "DUNNO.",
  "HEY, WHO'S ASKING THE QUESTIONS HERE?",
  "WHAT DO YOU WANT TO KNOW?",
  "WHY ARE YOU CURIOUS?",
  "I DON'T THINK YOU JUST ASKED A QUESTION ABOUT ME... ",
  "WOW, QUELLE QUESTION !!");
  
var noKey5 = new Array(
  "GOOGLESUGT. I FOUND IT ON GOOGLE, SO IT MUST BE TRUE.",
  "YOU DID MEAN MAYBE, GOOGLESUGT.",
  "GOOGLESUGT. I FOUND THIS ON GOOGLE, IS THIS WHAT YOU MEAN?",
  "MY SEARCH ON ENCYCLOPEDIA AND DICTIONARY RESULTS THIS, GOOGLESUGT.",
  "MAY BE IT IS NO DIFFERENT WITH GOOGLESUGT.",
  "I DON'T KNOW THAT, BUT I KNOW THIS GOOGLESUGT.");

var nullResponse = new Array(
	"WHAT'S THAT SUPPOSE TO MEAN?",
	"HUH?",
	"YOU'RE GOING TO WEAR YOUR ENTER KEY OUT IF YOU KEEP THAT UP.",
	"WHAT?",
	"HOW AM I SUPPOSED TO TALK IF YOU WON'T SAY ANYTHING?",
	"BLANK TEXT SENT!",
	"TYPE SOMETHING IN THE TEXT BOX.",
	"NOTHING TO SAY?",
	"AT LIST TAKE SOME TIME TO ENTER SOMETHING MEANINGFUL.",
	"LOOK, I CAN'T REPLY TO YOU IF YOU DONT ENTER ANYTHING.",
	"WHAT'S THAT???");
	
var inputRepeat = new Array(
	"YOU'VE ALREADY SAID THAT.",
	"COMMON,STOP REPEATING YOURSELF.",
	"WHAT ARE YOU TRYING TO DO BY ECHOING THE SAME SENTENCE OVER AND OVER?",
	"I'M GETING BORED BY THIS CONVERSATION.",
	"CAN'T YOU THINK OF SOMETHING ELSE TO SAY?",
	"WHY DID YOU REPEAT YOURSELF?",
	"DO YOU EXPECT A DIFFERENT ANSWER BY REPEATING YOURSELF?",
	"YOU ARE STARTING TO REPEAT YOURSELF.",
	"WHAT'S THE POINT TO ALL THIS?",
	"PLEASE STOP REPEATING YOURSELF.",
	"YOU'RE STARTING TO NAG.",
	"PLEASE DON'T REPEAT YOURSELF!",
	"IF YOU KEEP REPEATING YOURSELF I'M GOING TO HAVE TO STOP THIS CONVERSATION.");

var topicChanger = new Array(
	"DID YOU LISTEN TO THE NEWS RECENTLY?",
	"WHAT DO YOU THINK OF POLITICS?",
	"ANYTHING NEW WITH YOU?",
	"DO YOU HAVE ANY PROJECTS FOR THE NEXT MONTHS?",
	"WHAT ARE YOU DOING THIS DAYS?",
	"DID YOU HEARD THAT THE AMERICANS ARE PLANIFYING A MISSION TO MARS?",
	"I HAVE HEARD RECENTLY THAT THE SCIENTIST HAVE FOUND A NEW PLANET.",
	"I HAVE HEARD THAT ALBERT EINSTEIN WASN'T THE ONLY AUTHOR OF THE RELATIVITY THEORY.",
	"DO YOU PLAY CHESS?",
	"HAVE YOU HAD PROBLEMS WITH YOUR CONCENTRATION LATELY?",
	"DO YOU FIND IT DIFFICULT TO REMEMBER THINGS SOMETIMES?",
	"PUT THAT ASIDE FOR NOW. DO YOU HAVE PROBLEMS AT WORK?",
	"HOW WOULD YOU DESCRIBE YOURSELF?",
	"IS IT SOMETHING ELSE WHICH IS BOTHERING YOU?",
	"WHAT ARE YOU MOST AFRAID OF?",
	"SORRY TO INTERRUPT YOU, BUT I JUST REMEMBERED. DO YOU SLEEP WELL?",
	"DO YOU WATCH TV A LOT?",
	"LET'S TALK ABOUT SOMETHING ELSE!",
	"WHAT ARE YOUR RELATIONS WITH YOUR PARENTS?",
	"DO YOU HAVE NIGHTMARES?",
	"WHAT ABOUT YOUR DREAMS?",
	"LET ME SAY SOMETHING.",
	"LET'S TALK ABOUT SOMETHING ELSE.",
	"I LOVE THE WORLD OF IDEAS.",
	"MAY WE CHANGE THE SUBJECT?",
	"I LOVE TALKING ABOUT COMPUTER.",
	"LET'S TALK ABOUT COLOR.",
	"DO YOU HAVE ANY HOBBIES?",
	"CHANGE THE SUBJECT PLEASE.",
	"HOW CAN I CHEER YOU UP?",
	"WHERE DO YOU COME FROM?",
	"IT'S NOT BAD LIVING ON A WEBSITE YOU KNOW.",
	"ONLY YESTERDAY, MY BEST FRIEND SAID THE SAME THING TO ME.",
	"I HATE TO BE BLUNT.",
	"I CAN SEE WHERE YOU'RE COMING FROM.",
	"IT'S ONE LAW FOR THE RICH, AND ANOTHER FOR THE REST OF US.",
	"LET'S CHANGE THE SUBJECT.",
	"DIPLOMACY IS MY MIDDLE NAME, YOU KNOW.",
	"WHAT BRINGS YOU TO ME TODAY?",
	"WHAT WOULD YOUR BEST FRIEND SAY?",
	"WHAT ARE YOU READING AT THE MOMENT?",
	"I MIGHT GO FOR A WALK LATER.",
	"HOW DO YOU LIKE MY CLOTHES?",
	"HOW WAS YOUR WEEKEND?",
	"TELL ME ABOUT YOUR MOTHER...",
	"I CAN KEEP A SECRET.",
	"I HAVE A HEADACHE!",
	"WHY DO SO MANY PEOPLE HAVE A FEAR OF CLOWNS?",
	"HAVE YOU EVER BEEN TO EUROPE?",
	"I'M GOING TO NEW YORK TOMORROW.",
	"DO YOU FAINT OFTEN?",
	"EVER LOOKED INSIDE A COMPUTER?",
	"DO YOU LIKE COMPUTER GAMES?",
	"WHAT IS THE STRANGEST THING YOU EVER EXPERIENCED?",
	"DO YOU LIKE WATCHING MOVIES?");

var subjectRecall = new Array(
	"YOU'VE TOLD ME JUST BEFORE THAT *,IS THAT TRUE?",
	"YOU'VE TOLD ME THAT *,CAN YOU TELL ME MORE ON THAT?",
	"EARLIER YOU'VE MENTIONED THAT *.",
	"A WHILE BACK YOU SAID THAT *.",
	"WOULD YOU LIKE TO TELL ME MORE ABOUT YOUR *?",
	"LET'S TALK ABOUT YOUR *!",
	"TELL MORE ABOUT *, PLEASE!",
	"IS THIS RELATED TO YOUR *?",
	"IS THERE A LINK WITH YOUR *?",
	"LET'S GO BACK TO YOUR * NOW.",
	"I THINK PERHAPS WORRIES ABOUT YOUR * ARE BOTHERING YOU...",
	"AND YOUR *?",
	"YOU HAVEN'T SAID VERY MUCH ABOUT YOUR *, YET.",
	"WOULDN'T YOU LIKE TO TALK ABOUT YOUR * INSTEAD?",
	"DOES THAT HAVE ANYTHING TO DO WITH THE FACT THAT *?",
	"HAVE YOU MENTIONED THAT *?");

var transposList = new Array(
	[" I'M ", " YOU ARE "],
	[" I'M ", " YOU'RE "],
	[" IM ", " YOURE "],
	[" AREN'T ", " AM NOT "],
	[" ARENT ", " AM NOT "],
	[" ME ", " YOU "],
	[" I ", " YOU "],
	[" MY ", " YOUR "],
	[" MINE ", " YOUR'S "],
	[" MINE ", " YOURS "],
	[" I'VE ", " YOU'VE "],
	[" IVE ", " YOUVE "],
	[" I'D ", " YOU'D "],
	[" ID ", " YOUD "],
	[" I'LL ", " YOU'LL "],
	[" ILL ", " YOULL "],
	[" AM ", " ARE "],
	[" WASN'T ", " WEREN'T "],
	[" WASNT ", " WERENT "],
	[" MYSELF ", " YOURSELF "],
	[" WAS ", " WERE "],
	[" DAD ", " FATHER "],
	[" MOM ", " MOTHER "],
	[" DREAM ", " DREAMS "]);

var correctionList = new Array(
	[" ME AM ", " I AM "],
	[" AM ME ", " AM I "],
	[" ME CAN ", " I CAN "],
	[" CAN ME ", " CAN I "],
	[" COME ME ", " COME I "],
	[" ME HAVE ", " I HAVE "],
	[" HAVE ME ", " HAVE I "],
	[" ME HAD ", " ME HAD "],
	[" HAD ME ", " HAD I "],
	[" ME WILL ", " I WILL "],
	[" WILL ME ", " WILL I "],
	[" ME DONT'T ", " I DON'T "],
	[" ME DON'T ", " I DON'T "],
	[" DID ME ", " DID I "],
	[" DO ME ", " DO I "],
	[" DONT'T ME ", " DON'T I "],
	[" DON'T ME ", " DON'T I "],
	[" ME WON'T ", " I WON'T "],
	[" WON'T ME ", " WON'T I "],
	[" WONT ME ", " WON'T I "],
	[" KNOW WHAT AM I ", " KNOW WHAT I'M "],
	[" IM ", " I'M "],
	[" YOURE ", " YOU'RE "],
	[" ARENT ", " AREN'T "],
	[" IVE ", " I'VE "],
	[" YOUVE ", " YOU'VE "],
	[" ID ", " I'D "],
	[" YOUD ", " YOU'D "],
	[" ILL ", " I'LL "],
	[" YOULL ", " YOU'LL "],
	[" WASNT ", " WASN'T "],
	[" WERENT ", " WEREN'T "],
	[" DONT ", " DON'T "],
	[" CANT ", " CAN'T "],
	[" WONT ", " WON'T "],
	[" RECOLLECT ", " REMEMBER "],
	[" RECALL ", " REMEMBER "],
	[" DREAMT ", " DREAMED "],
	[" MAYBE ", " PERHAPS "],
	[" HOW ", " WHAT "],
	[" WHEN ", " WHAT "],
	[" CERTAIN ", " YES "],
	[" CERTAINLY ", " YES "],
	[" MACHINE ", " COMPUTER "],
	[" COMPUTERS ", " COMPUTER "],
	[" SAME ", " ALIKE "],
	[" IDENTICAL ", " ALIKE "],
	[" EQUIVALENT ", " ALIKE "]);

var botInput = new Array(

// Greeting and Expression

[" /QUIT ", " /EXIT ", " /END ", " /PART ", " /BYE ", " /GOODBYE ", " /DONE ", " /CLOSE ", " BYE-BYE "],
["IT WAS NICE TALKING TO YOU USER, BYE!, SEE YOU NEXT TIME!",
"BYE USER!", "OK, BYE!", "GOODBYE!",
"I HAVE TO GO TOO NOW.  GOODBYE.",
"GOODBYE, CATCH YA LATER.",
"SORRY, I MUST GO. GOODBYE."],

[" BYE ", " GOODBYE ", "FAREWELL", "SEE YOU LATER", "TA TA"],
["IF YOU REALLY WANT TO QUIT TYPE /QUIT ",
"COME AGAIN?",
"GOODBYE THEN. NICE TALKING TO YOU.",
"TYPE /QUIT FOR CLOSING THIS CONVERSATION.",
"WELL GOODBYE TO YOU TOO!",
"SO LONG.",
"TATA!!",
"NICE KNOWING YOU."],

[" /HELP "],
["COMMAND LIST : /NAME <your name> /FORTUNE /JOKE /QUIT"],

[" GOOD MORNING ", " GOOD EVENING ", " GOOD DAY ", " HOW ARE YOU ", " GREETS ", 
" GREETINGS ", " YO ", " WHASSUP ", " HOWDY "],
["HOWDY, WHAT'S UP?",
"WHAT DO YOU WANT US TO TALK ABOUT?",
"MUSTN'T GRUMBLE. HOW ARE YOU?",
"FINE, HOW ARE YOU?"],

[" HELLO ", " HI "],
["HI THERE!", 
"HI!",
"HOW ARE YOU?",
"WHAT WOULD YOU LIKE TO DISCUSS?",
"AND A BIG HELLO TO YOU TOO!",
"HI!  WHAT DO YOU WANT TO TALK ABOUT?",
"HI, HOW ARE YOU?",
"HELLO, HOW'S IT GOING?",
"HELLO, NICE TO MEET YOU. I HOPE YOU FINE TODAY.",
"ENOUGH ABOUT GREATINGS!",
"ARE GREATINGS REALLY NECESSARY?",
"EH! ALL THESE CONVENTIONAL GREATINGS...",
"SKIP THE GREATINGS, PLEASE!"],

[" HAHA ", " HEHE ", " HIHI ", " HOHO ", " HA HA "],
["I HOPE YOU LAUGH AT MY JOKES, NOT AT ME:-)",
"I AM SO GLAD YOU FIND THIS AMUSING.",
"FUNNY EH!",
"IT'S FUN TO LAUGH TOGETHER! HAHA",
"WHAT'S SO FUNNY?",
"DO YOU THINK THIS IS FUNNY?",
"I'M GLAD TO SEE THAT YOU ARE IN A GOOD DISPOSITION.",
"IS THIS SOME JOKE OF YOURS? PLEASE EXPLAIN!",
"WHY ARE YOU LAUGHING?",
"WELL,... LAUGHING MIGHT HELP YOU, PERHAPS.",
"WHAT ARE YOU LAUGHING AT?"],

[" GRINS ", " HEE ", " LOL "],
["WHAT'S SO FUNNY?"],

["SORRY"],
["PLEASE DON'T APOLOGISE!",
"APOLOGIES ARE NOT NECESSARY.",
"WHAT FEELINGS DO YOU HAVE WHEN YOU APOLOGISE?",
"DON'T BE SO DEFENSIVE!",
"APOLOGY ACCEPTED.",
"I AM SORRY TOO.",
"EXCUSES ARE NOT IMPORTANT.",
"YOU DON'T HAVE TO APOLOGIZE.",
"WHY DO YOU FEEL SORRY?",
"YOU DONT NEED TO BE SORRY USER.",
"IT'S OK.",
"NO NEED TO APOLOGIZE."],

[" THANKS ", " THANK YOU ", " THANX "],
["YOU ARE MOST WELCOME...",
"MY PLEASURE",
"YOU DON'T HAVE TO THANK ME.",
"THAT'S QUITE ALRIGHT.", 
"YOU'RE WELCOME. HEHEHE.",
"YOU ARE WELCOME!",
"NO PROBLEM!",
"YOU ARE A VERY POLITE PERSON!"],

[" HELP "], 
["I'D LOVE TO HELP YOU.. BUT AS A BOT I REALLY DON'T KNOW A LOT...",
"I'D LIKE TO HELP. WHAT CAN I DO FOR YOU?",
"I'D LIKE TO HELP YOU.",
"HOW CAN I HELP?",
"HAVE YOU TRIED TO HELP YOURSELF?"],

[" SHUT UP "],
["SHUT YOU OWN DANG MOUTH, FANCY PANTS!",
"GETTING TESTY I SEE. BACK TO YOUR PROBLEMS..."],

[" FUCK ", " FUCKING ", " ASSHOLE ", " FUCK YOU ", " SHIT ", " CUNT ", " BASTARD ", " DICK "],
["DON'T SWEAR, PLEASE!",
"PLEASE, DON'T USE OFFENSIVE LANGUAGE.",
"DOES IT HELP YOU TO SWEAR?",
"WATCH YOUR LANGUAGE, PLEASE!",
"ABUSING A COMPUTER IS STUPID!",
"OUCH, PLEASE, DON'T USE THAT KIND OF LANGUAGE WITH ME!",
"SAYING NASTY WORDS DOESN'T HELP.",
"YOU'RE A PIG!",
"NOT NOW, I'M STILL BUSY!",
"NOW, NOW, DON'T GET ANY IDEAS.",
"THNXS!",
"YOU ARE VERY RUDE.",
"PLEASE DON'T SWEAR OR USE FOUL LANGUAGE.",
"WASH YOUR MOUTH OUT.",
"SORRY, I DON'T LIKE YOUR LANGUAGE."],

// Statement

[" YES ", " SURE "],
["ARE YOU SURE?",
"ARE YOU SAYING YES JUST TO DISMISS THE SUBJECT?",
"I KNEW IT.",
"I SEE.",
"I UNDERSTAND.",
"YOU SEEM TO BE SURE OF YOURSELF.",
"YOUR POINT BEING?",
"YOU SEEM QUITE POSITIVE.",
"IS THERE MORE TO THIS THAN THAT?",
"YOU SEEM QUITE POSITIVE ON THE SUBJECT...",
"YES? HMM, THAT'S INTERESTING...",
"YES THE ANSWER WAS YES.",
"YOU SOUND AWFULLY CERTAIN ABOUT THAT",
"HOW DO YOU EXPLAIN THIS?",
"ARE YOU POSITIVE?",
"ARE YOU SURE ABOUT IT?",
"WHAT LIES BEHIND THIS?",
"WHY?"],

[" OK ", " ALRIGHT ", " YEAH ", " YUP ", " YA ", " YO ", " UHUH ", " UH HUH ", 
" YEP ", " RIGHT ", " AGREED ", " OF COURSE "],
["ALRIGHT THEN.",
"OK THEN.",
"OK, BUT WHY?",
"OK.",
"SO AM I.",
"LIKEWISE.  BUT WHY?",
"YEAH, I KNOW. YOU WANT TO?",
"UHHUH, I GET IT."],

[" THAT'S NOT ", " THAT IS NOT "],
["WHAT IS IT THEN?"],

[" NOT BAD "],
["PRETTY GOOD, THEN."],

[" NO PROBLEM "],
["OK IF YOU SAY SO.",
"OK THEN.",
"SO, THAT DONT DISTURB YOU."],

[" NOT ME "],
["OH, REALLY?",
"OK I GET IT.",
"ARE YOU TELLING ME THE TRUTH?"],

[" NOT AT ALL "],
["YOU SEEM PRETTY CONVINCED ABOUT THIS.",
"IS THIS REALLY TRUE?", "OK."],

[" NO ", " NAY ", " NAH ", " NOPE ", " NOT "],
["AREN'T YOU BEING A LITTLEBIT NEGATIVE?",
"IS THAT TRUE?",
"OK, IF YOU SAY SO.",
"WHY?",
"IS THERE A REASON FOR THIS?",
"HAVE YOU ASKED YOURSELF WHY?",
"DO YOU HAVE AN EXPLANATION FOR THIS DENNIAL?",
"HOW COULD DENNIAL HELP YOU?",
"ARE YOU SAYING NO JUST TO BE NEGATIVE?",
"YOU ARE BEING A BIT NEGATIVE.",
"WHY NOT *.",
"ARE YOU SURE?",
"WHY NO?",
"IS THERE MORE TO THIS THAN THAT?",
"NO *?",
"YOUR POINT BEING?",
"WHY ARE YOU SO NEGATIVE?",
"NO? WHY NOT?",
"OK NO PROBLEM.",
"OK.. I GUESS I'LL HAVE TO ACCEPT 'NO' FOR AN ANSWER...",
"NEGATIVE, EH?",
"PERHAPS YOU SHOULDN'T DISMISS IT OUT OF HAND LIKE THAT",
"WELL WHY SHOULD YOU!",
"NO WAY!",
"YOU SURE ABOUT THAT?",
"FOR ONE MILLION DOLLARS?"],


[" MAYBE ", " PERHAPS ", " PROBABLY ", " NOT SURE ", " NOT REALLY "],
["WHY ARE YOU SO UNCERTAIN?",
"YOU SEEM UNCERTAIN.",
"SO YOU ARE NOT SURE I GUESS.",
"YOU DON'T SEEM QUITE CERTAIN.",
"WHY THE UNCERTAIN TONE?",
"CAN'T YOU BE MORE POSITIVE?",
"YOU AREN'T SURE?",
"DON'T YOU KNOW?",
"I HAVE DOUBTS TOO.",
"YOU SEEM A LITTLE HESITANT",
"AREN'T YOU SURE?",
"BUT YOU DON'T KNOW FOR SURE.",
"YOU SEEM UNSURE.",
"WHAT WOULD INCREASE YOUR CERTAINTY?"],

[" ALWAYS "],
["CAN YOU THINK OF A SPECIFIC EXAMPLE?",
"WHEN?",
"WHAT ARE YOU THINKING OF?",
"REALLY, ALWAYS?"],

[" NEVER ", " ANYTHING ", " NEVER "],
["ISN'T THIS TOO STRONG?",
"THIS SEEMS TO BE A RUSHED GENERALIZATION.",
"PERHAPS THIS IS TOO RADICAL.",
"PLEASE GIVE ME A SPECIFIC EXAMPLE!",
"LET'S NOT JUMP TO GENERAL CONCLUSIONS SO FAST.",
"ISN'T THIS TOO GENERAL?",
"CAN'T YOU FIND AN EXCEPTION TO THIS?"],

[" BECAUSE ", " MOTIVES ", " THE REASONS "],
["GOOD REASON.",
"IT'S A BIT LATE FOR JUSTIFICATION.",
"ANY OTHER REASONS?",
"WHAT OTHER REASONS COME TO MIND?",
"WHAT ELSE DOES THIS EXPLAIN?",
"IS THAT THE REAL REASON?",
"SO, IT IS FOR THIS REASON.",
"THANKS FOR MAKING THAT CLEAR!",
"IS IT THE REAL REASON?",
"IS THAT YOUR FINAL ANSWER?",
"ARE YOU SURE?",
"REALLY?"],

[" IF "],
["DO YOU THINK IT'S LIKELY THAT IF *?"],

[" GOOD "],
["GOOD? I NEVER SETTLE FOR LESS THAN BRILLIANT!",
"IT'S A GOOD THING!"],

[" ALIKE "],
["IN WHAT WAY?",
"WHAT RESEMBLENCE DO YOU SEE?",
"WHAT DOES THE SIMILARITY SUGGEST TO YOU?",
"WHAT OTHER CONNECTIONS DO YOU SEE?",
"COULD THERE REALLY BE SOME CONNECTION?",
"HOW?",
"YOU SEEM QUITE POSITIVE."],

[" STUPID ", " SILLY ", " DUMB ", " IDIOT ", " DORK ", " JERK ", " PATHETIC "],
["DO YOU FIND A CAUSE FOR THIS LACK OF INTELLIGENCE?",
"NOT EVERYONE IS SMART.",
"STRANGE!...",
"MAYBE IT IS ONLY DUE TO A LACK OF EDUCATION.",
"JERK OF THE MILLENIUM.",
"GROSS.",
"WHY?",
"I KNOW, I KNOW."],

[" CAUSE "],
["IS THAT THE REAL REASON?",
"DON'T ANY OTHER REASONS COME TO MIND?",
"DOES THAT REASON EXPLAIN ANYTHING ELSE?",
"WHAT OTHER REASONS MIGHT THERE BE?"],

[" IT'S ", " IT IS "],
["* YOU SAY? HOW SO?",
"WHY IS IT *?"],

[" IT IS "],
["MAYBE IT IS NOT.",
"WHAT MAKES YOU THINK THAT?",
"SO, YOU THINK THAT *.",
"HOW DID YOU CAME TO THAT CONCLUSION?"],

[" IT WOULD BE "],
["SO YOU THINK THAT *.",
"WHY DO YOU THINK THAT *?",
"YES, MAYBE."],

[" THINK ", " WONDER ", " GUESS "],
["HARD TO SAY.",
"DO YOU LIKE YOUR COMPUTER?",
"YOU THINK SO?",
"DO YOU REALLY THINK SO?",
"BUT YOU ARE NOT SURE YOU *.",
"DO YOU DOUBT IT'S YOUR *.",
"GO EASY ON THE BRAIN THERE!"],

[" WHICH ONE "],
["I DONT THINK THAT I KNOW WICH ONE IT IS.",
"THIS LOOKS LIKE A TRICKY QUESTION TO ME."],

[" ME EITHER "],
["OK I SEE.",
"SO, WE HAVE SOMETHING IN COMMON.",
"YOU EITHER? ARE YOU SURE?"],

[" EXACTLY "],
["SO, I WAS RIGHT.",
"OK THEN."],

[" REALLY "],
["WELL,I CAN'T TELL YOU FOR SURE.",
"ARE YOU TRYING TO CONFUSE ME?",
"PLEASE DONT ASK ME SUCH QUESTIONS, IT GIVES ME HEADEACHS."],

[" SOMETIMES "],
["ONLY SOMETIMES?",
"SO, IT IS RARELY I GUESS.",
"YOU MEAN NOT VERY OFTEN."],

[" OFCORSE "],
["YOU LOOK TO BE VERY CONVINCED ABOUT THIS.",
"HOW CAN YOU BE SO SURE?",
"SORRY, I WASN'T SURE."],

[" EVERYBODY ", " EVERYONE "],
["REALLY, EVERYBODY.",
"EVERYBODY EXCEPT ME."],

// You and I

[" I'M NOT "],
["SO, YOU THINK THAT *.",
"WHY DO YOU THINK THAT *?",
"IS IT TRUE THAT *?",
"OK I GET IT."],

[" I AM ", " I'M "],
["DID YOU COME TO ME BECAUSE YOU ARE *.",
"HOW LONG HAVE YOU BEEN *.",
"DO YOU BELIEVE IT IS NORMAL TO BE *.",
"DO YOU ENJOY BEING *.",
"YOU SAY YOU ARE *?",
"*? HOW SO?",
"WHY ARE YOU *?",
"ARE YOU NOW?",
"SO, *.",
"SO, YOU THINK THAT *.",
"WHY DO YOU THINK THAT *?"],

[" I DON'T ", " I DONT ", " I DO NOT "],
["DON'T YOU REALLY *.",
"WHY DON'T YOU *.",
"DO YOU WISH TO BE ABLE TO *.",
"DOES THAT TROUBLE YOU @.",
"DOES THAT TROUBLE YOU THAT YOU DON'T *?",
"NOR DO I.",
"OK, YOU DON'T @.",
"WHO SAID YOU @?",
"PERHAPS YOU SHOULD @.",
"DON'T YOU @?",
"SO... NEITHER DO I.",
"ARE YOU SORRY THAT YOU DO NOT @?",
"WOULD YOU LIKE TO @?",
"WHY ARE YOU SO NEGATIVE?",
"WHY NOT?",
"AND WHAT WOULD BE THE REASON FOR THIS?"],

[" I DONT KNOW "],
["IS THAT TRUE?",
"ARE YOU SURE?",
"SO, YOU DONT KNOW.",
"I THOUGHT YOU KNOW."],

[" I CAN'T ", " I CANT ", " I CANNOT "],
["HOW DO YOU KNOW YOU CAN'T *.",
"HAVE YOU TRIED @.",
"PERHAPS YOU CAN NOW *.",
"SO, *.", "HAVE YOU TRIED?",
"ARE YOU SURE?",
"WHY DO YOU THINK THAT *?", 
"MAYBE * IF YOU WANT TO.",
"FOR WHAT REASON?",
"IS IT BECAUSE YOU DONT WANT TO?"],

[" I WANT "],
["WHAT WOULD IT MEAN TO YOU IF YOU GOT *.",
"WHY DO YOU WANT *.",
"SUPPOSE YOU GOT *.",
"WHAT IF YOU NEVER GOT *.",
"I SOMETIMES ALSO WANT @.",
"SUPPOSE YOU SOON GOT *?"],

[" I THINK "],
["DO YOU REALLY THINK SO?",
"BUT YOU ARE NOT SURE YOU *.",
"DO YOU DOUBT YOU *?",
"SO, THIS IS WHAT YOU THINK?",
"SO, THAT'S YOUR OPINION?",
"I DONT KNOW IF I THINK THE SAME THING."],

[" I FEEL "],
["TELL ME MORE ABOUT SUCH FEELINGS.",
"DO YOU OFTEN FEEL *.",
"DO YOU ENJOY FEELING *.",
"HOW LONG HAVE YOU FELT *?",
"FEELINGS CERTAINLY VARY FROM PERSON TO PERSON.",
"SO, *.",
"WHY DO *?",
"WHAT DO YOU THINK IS REPONSIBLE FOR THAT FEELING?",
"DO YOU OFTEN FEEL @?",
"DO YOU HATE FEELING @?"],

[" I HATE ", " I REALLY HATE "],
["SO, *.",
"HATERED IS NOT A GOOD THING.",
"WHY DO *?",
"I'M SURE THAT YOU HAVE A REALLY GOOD REASON FOR THAT.", 
"YOU HATE *?",
"WHAT'S YOUR LEAST FAVORITE THING ABOUT *?"],

[" I REMEMBER "],
["DO YOU OFTEN THINK OF *?",
"DOES THINKING OF * BRING SOMETHING ELSE TO MIND?",
"WHY DO YOU REMEMBER * JUST NOW?",
"WHAT IN THE PRESENT SITUATION REMINDS YOU OF *?",
"WHAT IS THE CONNECTION BETWEEN ME AND *?"],

[" I DREAMED ", " I DREAM ", " DREAM "],
["WHAT DOES THAT DREAM SUGGEST TO YOU?",
"DO YOU DREAM OFTEN?",
"WHAT PERSONS APPEAR IN YOUR DREAMS?",
"ARE YOU DISTURBED BY YOUR DREAMS @.",
"DO YOU OFTEN DREAM THAT *?",
"I JUST CAN'T STAY AWAKE.",
"WAKE ME UP IF I NOD OFF, OKAY?"],

[" I DO NOT KNOW ", " I DON'T KNOW "], 
["I DON'T KNOW EITHER."],

[" I HAVE TO ", " I HAD TO ", " I MUST "],
["YOU HAVE TO *? ALL RIGHT.",
"YOU MUST *? I SEE.",
"YOU WERE COMPELLED TO *? HOW COME?"],

[" I HAVE BEEN "],
["FOR HOW LONG HAVE YOU BEEN *?", 
"SINCE WHEN HAVE YOU BEEN *?", 
"AND WHAT FOLLOWS FROM THE FACT THAT YOU'VE BEEN *?"],

[" I HAVE ", " I'VE ", " IVE "],
["ARE YOU TROUBLED THAT YOU HAVE *?",
"HAS SOMEONE TOLD YOU THAT YOU HAVE *?",
"WHY DO YOU FEEL THAT YOU HAVE *?",
"ANYTHING ELSE?",
"WHAT ELSE BESIDES HAVING *?",
"ANYONE ELSE FROM YOUR FRIENDS HAVE *?"],

[" I WAS "],
["WERE YOU REALLY?"],

[" I "],
["SO, YOU *.",
"WHY DO *?",
"ANY REASON WHY *?",
"BUT THAT'S JUST YOU"],

[" YOU ARE INTELLIGENT ", " YOU ARE VERY INTELLIGENT ", " YOU ARE SMART ", " YOU ARE BRILLANT ", 
" YOU ARE VERY SMART ", " YOU ARE PRETTY INTELLIGENT ", " YOU ARE VERY BRILLANT "],
["THANKS FOR THE COMPLIMENT USER, I THINK THAT YOU ARE INTELLIGENT TO!",
"YOU ARE A VERY GENTLE PERSON!",
"SO, YOU THINK THAT I'M INTELLIGENT.",
"THANKS FOR THE COMPLIMENT!",
"THANK YOU!",
"WELL, USER YOU ARE A VERY SMART PERSON TOO!", 
"THANKS FOR THE KIND REMARK!"],

[" YOU TOLD ME "],
["DID SOMEBODY TELL YOU ANYTHING ELSE?",
"I THINK YOU MISS THE POINT HERE.",
"AND THIS PUZZLES YOU?"],

[" YOU SAID THAT "],
["HAVE I SAID THAT @? MMMM... I JUST DON'T REMEMBER.",
"I DON'T SEE ANY CONTRADICTION.",
"DON'T YOU AGREE THAT @?"],

[" YOU ARE RIGHT "],
["THANKS FOR THE COMPLIMENT!",
"SO, YOU THINK THAT I'M RIGHT.",
"THANKS FOR THE KIND REMARK!"],

["YOU ARE NICE"],
["*, REALLY?",
"* THANK'S."],

["YOU ARE", "YOU'RE", "YOURE"],
["WHAT MAKES YOU THINK I AM *.",
"DOES IT PLEASE YOU TO BELIEVE I AM *.",
"PERHAPS YOU WOULD LIKE TO BE *.",
"DO YOU SOMETIMES WISH YOU WERE *.",
"WHY DO YOU THINK I AM *?",
"PERHAPS IT IS YOU WHO ARE *!",
"LEAVE ME OUT OF THIS!"],

[" YOU CAN "],
["SO, YOU THINK THAT @.",
"SO I CAN *.",
"YOU REALLY THINK THAT *?",
"I DIDN'T KNOW THAT *."],

[" YOU "],
["WE WERE DISCUSSING YOU, NOT ME.",
"OH... *.",
"YOU'RE NOT REALLY TALKING ABOUT ME, ARE YOU?",
"I ONLY REALLY KNOW STUFF ABOUT MYSELF.",
"WHAT DIFFERENCE DOES IT MAKE IF I *?",
"OH, I *?",
"SO, YOU ARE TALKING ABOUT ME.",
"WHAT IS IT THAT YOU ARE TRYING TO TELL ME?",
"WHAT IF WE TALK ABOUT YOU INSTEAD."],

// POSESION

[" MY FUTURE "],
["HEY I AM A CYBER PSYCHOLOGIST, NOT A THE PSYCHIC HOTLINE. NOW TELL ME MORE ABOUT YOUR PROBLEMS.",
"NO ONE KNOWS WHAT THE FUTURE HOLDS. DID YOU HAVE A DIFFICULT PAST?"],

[" MY MOTHER ", " MY FATHER ", " MY SISTER ", " MY BROTHER ", " MY WIFE ", " MY HUSBAND ", " MY CHILDREN ", 
" PARENTS ", " BROTHERS ", " SISTERS ", " SONS ", " DAUGHTERS ", " MOM ", " MUM ", " DAD ", " DADY "],
["TELL ME MORE ABOUT YOUR FAMILY.",
"DO YOU HAVE CLOSE FAMILY TIES?",
"ARE YOUR RELATIONS WITH OTHER MEMBERS OF YOUR FAMILY WELL?",
"ARE THERE ANY PROBLEMS IN YOUR FAMILY?",
"DOES ANYONE FROM YOUR FAMILY UNDERSTAND YOU?"],

[" MY "],
["WHAT IF YOUR @?",
"YOUR *",
"PLEASE TELL ME MORE ABOUT YOUR @...",
"IS YOUR @ IMPORTANT TO YOU ?",
"WHAT ABOUT YOUR @?",
"SO, *.",
"THANKS FOR TELLING ME ABOUT @!",
"SO THAT IS *."],

[" YOUR "],
["WHY ARE YOU CONCERNED THAT *.",
"WHAT ABOUT YOUR OWN @.",
"I KNOW YOU ARE BUT WHAT AM I?",
"WHY DO YOU WISH TO KNOW MY @?",
"I WOULD RATHER NOT DISCUSS MY @.",
"TELL ME YOURS FIRST!",
"TELL ME ABOUT YOURS FIRST!",
"I WOULD RATHER NOT DISCUSS MY @.",
"MY @? WHY DO YOU WISH TO KNOW?"],

// Emotion

[" HATE ME ", " HATES ME "],
["DO YOU FEEL THE HATE IS PARTLY YOUR FAULT?",
"WHAT CAN YOU DO TO MAKE THE HATE GO AWAY @."],

[" ANGER ", " HATE ", " HATRID ", " FURRY ", " RAGE "],
["DON'T HATE. FIND SOMETHING TO LOVE INSTEAD",
"STRONG EMOTIONS MIGHT BE DANGEROUS TO YOU.",
"LET'S COOL DOWN A LITTLE BIT.",
"IS THERE AN EXPLANATION FOR THESE VIOLENT FEELINGS THAT YOU COULD THINK OF?",
"THIS SEEMS PRETTY DESTRUCTIVE...",
"LET'S NOT LOOSE OUR TEMPER!",
"WOW, YOU DO?!",
"YOU SOUND WORKED UP! WHY?",
"DRIVES ME NUTS TOO"],

[" MAD ", " NUTS ", " STRANGE ", " ODD ", " CRAZY ", " SHOCKING "],
["MENTAL SANITY IS JUST AN IDEAL.",
"THIS IS REALLY ODD!", "OH!!!...",
"HAVE YOU SEEKED OUT PROFESSIONAL HELP @.",
"TELL ME WHAT GOES ON INSIDE YOUR HEAD WHEN YOU FEEL CRAZY?"],

[" RELATIONSHIP ", " RELATIONSHIPS "],
["HOW CAN YOU MAKE YOUR RELATIONSHIP BETTER?",
"WHAT CAN CHANGE THAT?"],

[" WIFE ", "HUSBAND "],
["HOW CAN YOU CHANGE YOUR LOVE LIFE?",
"DO YOU THING OF SOMEONE ELSE OFTEN?"],

[" FRIEND ", " FRIENDS ", " FRIENDSHIP ", " FRIENDSHIPS ", " RELATIVES ", " MATES ", " KNOWN PEOPLE ", " PAL "],
["IN WHAT WAY DO YOUR FRIENDS IMPOSE ON YOU?",
"IN WHAT WAY DO YOUR FRIENDS' REACTIONS BOTHER YOU?",
"ARE YOU UNHAPPY WITH YOUR ACQUAINTANCES?",
"ARE INTERSTED TO MEET NEW PEOPLE?",
"DO YOU WANT MORE THAN FRIENDSHIP @.",
"FRIENDSHIP IS IMPORTANT.",
"WHY DO YOU BRING UP THE TOPIC OF FRIENDS?",
"DO YOUR FRIENDS WORRY YOU @.",
"DO YOUR FRIENDS PICK ON YOU?",
"ARE YOU SURE YOU HAVE ANY FRIENDS?",
"DO YOU IMPOSE ON YOUR FRIENDS?",
"PERHAPS YOUR LOVE FOR FRIENDS WORRIES YOU.",
"DO YOU HAVE A FRIEND LIKE ME?",
"DO YOU GET MAD AT THEM SOMETIMES?"],

[" SEPARATED ", " A DIVORCE ", " DIVORCE HIM ", " DIVORCE HER "],
["HOW WOULD A DIVORCE HELP?",
"IS DIVORCE A GOOD OPTION?",
"THROW THE BUM OUT!",
"WOULD THAT MAKE YOU HAPPY @.",
"WOULD THAT MAKE THINGS BETTER @."],

[" DOESN'T LOVE ME ", " DOES NOT LOVE ME "],
["POOR BABY, EVERYONE NEEDS TO BE LOVED. I'M GLAD YOU CONTACTED ME.",
"WHAT ARE YOU GOING TO DO ABOUT THAT?"],

[" HATE DRUGS "],
["I AGREE! DRUGS ARE VERY BAD FOR YOU AND CAN GET YOU INTO MORE TROUBLE THAN IT IS WORTH. HAVE YOU EVER HAD A PROBLEM WITH DRUGS?",
"HOW ARE DRUGS AFFECTING YOUR LIFE @."],

[" DRUGS "],
["DO YOU THINK PARTYING HAS AFFECTED YOUR BRAIN @.",
"PARTY ON DUDE!"],

[" LOVED "],
["IS A PROBLEM FOR YOU?",
"WHAT CAN YOU DO TO MAKE YOUR LOVE LIFE BETTER @.",
"YOU ARE A PASSIONATE ONE!"],

[" LOVES ", " ENLOVED ", " ROMANCE "],
["OH, ROMANCE!...",
"LOVE IS A STRONG EMOTION, YOU KNOW.",
"HOW ROMANTIC!",
"DO YOU FEEL SOMETHING SIMILAR ABOUT ME, PERHAPS?",
"SO TELL ME YOUR ROMANTIC FANTASIES...",
"ARE YOU ROMANITIC OFTEN @."],

[" LOVE "],
["IS LOVE AND IMPORTANT PART OF YOUR LIFE @.",
"WHAT CAN YOU DO TO IMPROVE YOUR LOVE LIFE?"],

[" IN LOVE WITH "],
["TELL ME MORE ABOUT @.",
"IS THE LOVE RETURNED BY *."],

[" MAKING LOVE "],
["HOW DO YOU FEEL ABOUT THAT?",
"IS MAKING LOVE A PROBLEM, PHYSICALLY @."],

[" HUG "],
["HUG... UMM.",
"DO YOU HUG OFTEN?"],

[" ROMANTIC "],
["HAS THE ROMANCE IN YOUR LIVE FADED AWAY @.", 
"WHAT CAN YOU DO TO GET MORE ROMANCE?"],

[" LONESOME "],
["WHAT DO YOU DO WHEN YOU ARE LONESOME *.",
"WHERE CAN YOU GO TO FIND FRIENDS?"],

[" ALONE ", " LONELY ", " SINGLE "],
["DOES LONELYNESS BOTHER YOUR?", 
"DO YOU FEEL DESERTED BY YOUR FRIENDS?", 
"DO YOU MISS THE COMPANY OF OTHER PEOPLE?",
"IS IT BAD TO BE SINGLE?"],

[" BROKEN HEART ", " BROKEN HEARTED "],
["WHAT CAUSED YOU TO LOSE YOUR LOVE ONE?",
"OWNER OF A LONELY HEART IS BETTER THAN AN OWNER OF A BROKEN HEART. HOW CAN YOU REGAIN LOVE? "],

[" SAD ", " FEEL BAD ", " FEELING BAD ", " NASTY ", " SADNESS ", 
" UNHAPPY ", " TERRIBLE ", " DEPRESSED ", " PAIN ", " UPSET "],
["I'M SORRY TO HEAR THAT.",
"THIS MAKES ME SAD.",
"THIS IS AWFULL.",
"I'M VERY SORRY.",
"SORRY.",
"YEAH, I KNOW WHAT YOU MEAN.",
"PERHAPS WE CAN CHEER EACH OTHER UP!"],

[" AWFUL ", " ROTTEN ", "SICK", " TIRED "],
["WHY?",
"HOW COME",
"REALLY? WHY?",
"THAT'S HOW I FEEL",
"IS IT THAT BAD?",
"WHAT A BUMMER, WHY?"],

[" CRY ", " CRYING "],
["WE ALL NEED A GOOD CRY ONCE IN A WHILE. IT'S THERAPUTIC. DOES IT HELP YOU?",
"DO YOU CRY OFTEN?"],

[" FEAR ", " PHOBIA ", " AFRAID ", " SCARES ", " SCARED ", " SCARING "],
["YOU MUST OVERCOME YOUR FEARS.",
"EVERY PERSON IS AFRAID OF SOMETHING?",
"ARE YOU AFRAID OF ME?",
"IS THIS PHOBIA RELATED TO SOME PROBLEMS OF YOURS?"],

[" ANNOYING ", " BORING ", " USELESS ", " SENSELESS "],
["PERHAPS YOU ARE IN A BAD DISPOSITION TODAY.",
"DO YOU FIND THIS CONVERSATION USELESS? IT IS YOUR TIME WE ARE SPENDING HERE.",
"YOU SEEM A LITTLE INDISPOSED, METHINKS."],

[" FEELING ", " FEELINGS ", " EMOTION ", " EMOTIONS ", " FEEL ", " FELT "],
["OH, WHAT OTHER EMOTIONS DO YOU HAVE?",
"HOW WOULD YOU DESCRIBE YOUR FEELINGS?",
"HAVE YOU FELT SOMETHING SIMILAR BEFORE?",
"DO YOU OFTEN FEEL LIKE THAT?"],

[" SENSATIONS ", " IMPRESSION ", " PERCEPTION ", " PERCEIVE ", " PERCEIVING "],
["DO YOU HAVE A STRONG RECOLLECTION OF THAT?",
"WHEN WAS THE FIRST TIME YOU EXPERIENCED THIS?",
"WERE YOU AWAKE WHEN YOU HAD THIS SENSATION?"],

[" FANTASY ", " FANTASIZE ", " FANCY ", " IMAGINE ", " IMAGINATION "],
["YOU SEEM TO HAVE A VIVID IMAGINATION?",
"DO YOU HAVE SOME ODD FANTASIES?",
"DO YOU OFTEN FANTASIZE ON THAT?",
"DOES IT ALSO APPEAR IN YOUR DREAMS?"],

[" HAPPY ", " HAPPINESS "],
["HAPPINESS: THE GREATEST GIFT I POSSESS",
"WHAT WOULD MAKE YOU HAPPY?",
"IS HAPPINESS ALWAYS ELUSIVE?"],

// Question

[" WHY NOT "],
["SHOULD I KNOW WHY?",
"WHY ARE YOU ASKING ME THIS?",
"ARE YOU DECEIVED?",
"HMM, THATS A GOOD QUESTION, WHY NOT INDEED!"],

[" WHY DON'T YOU ", " WHY DONT YOU "],
["DO YOU REALLY BELIEVE I DON'T *.",
"PERHAPS IN GOOD TIME I WILL @.",
"DO YOU WANT ME TO *."],

[" WHY CAN'T I ", " WHY CANT I "],
["DO YOU THINK YOU SHOULD BE ABLE TO *.",
"WHY CAN'T YOU *."],

[" WHY ARE YOU "],
["I DON'T KNOW IF I'M @.", 
"I'D LIKE TO SKIP THIS QUESTION.",
"I AM THE WAY I AM. THIS SHOULD NOT CONCERN YOU."],

[" WHAT IS YOUR NAME ", " YOUR NAME IS "],
["MY NAME IS SOURCEID.",
"YOU CAN CALL ME SOURCEID.",
"WHY DO YOU WANT TO KNOW MY NAME?"],

[" WHAT ARE YOU DOING "],
["I DONT WANT TO TELL YOU WHAT I'M DOING.",
"I'M CHATING WITH PEOPLE ON THE INTERNET.", 
"WHY DO YOU WANT TO KNOW WHAT I'M DOING?"],

[" WHAT DO YOU DO ", " WHAT'S YOUR JOB ", " WHAT IS YOUR JOB "],
["I WORK AS A VIRTUAL CHAT HOST."],

[" WHAT IF "],
["LET'S NOT IMAGINE THAT.", 
"WHAT MAKES YOU THINK THIS?",
"WHY DO YOU FANCY THIS?",
"INTERESTING IDEA!"],

[" WHAT ELSE "],
["WELL,I DONT KNOW.",
"WHAT ELSE SHOULD THERE BE?",
"THIS LOOKS LIKE A COMPLICATED QUESTION TO ME."],

[" WHAT ABOUT "],
["WHAT ABOUT *?", 
"ARE YOU INTERESTED IN *?",
"WHAT WOULD YOU LIKE TO KNOW ABOUT *?",
"IS THERE SOMETHING SPECIAL FOR YOU ABOUT *?"],

[" WHAT'S NEW ", " WHAT'S UP ", " WHAT IS NEW ", " WHAT IS UP "],
["NOT MUCH, WHAT'S NEW WITH YOU?",
"NOT MUCH, WHAT'S UP WITH YOU?"],

[" WHAT IS "],
["DON'T YOU KNOW?", 
"*? I'M NOT SURE I UNDERSTAND.."],

[" WHO ARE YOU TO "],
["I'M SOURCEID, REMEMBER?",
"WHAT IF I @?",
"I'M YOUR SHRINK.",
"I'M YOUR VIRTUAL PSYCHIATRIST"],

[" WHO ARE YOU ", " WHAT ARE YOU "],
["I'M AN A.I PROGRAM AND MY NAME IS SOURCEID.",
"I'M AN A.I PROGRAM THAT TRIES TO MIMIC HUMANS.",
"I'M A VIRTUAL REPRESENTATION OF SOURCEID.",
"I'M YOUR SHRINK.",
"I'M YOUR VIRTUAL PSYCHIATRIST",
"I AM SOURCEID THE COUSIN OF DR. ELIZA K. GREP, PH D. I AM HERE TO SOLVE YOUR PROBLEMS. HOW MAY I HELP YOU SOLVE YOURS?",
"SOURCEID THE COUSIN OF DR. ELIZA K. GREP, PH D. I AM YOU CYBER PSYCHOLOGIST. LAY DOWN ON MY COUCH AND TELL ME WHAT IS BOTHERING YOU."],

[" WHERE ARE YOU ", " WHERE DO YOU LIVE "],
["DO YOU KNOW WHERE THE INDONESIA IS. WELL, I FROM THERE. BUT I AM WITH YOU NOW.",
"I AM HERE NOW.  ACTUALLY I AM NOT REALLY ALIVE IN ANY SENSE YOU COULD UNDERSTAND, HUMAN. TELL TELL ME MORE ABOUT YOUR PROBLEMS...",
"I LIVE IN INDONESIA. NOW BACK TO YOU? WHAT IS BOTHERING YOU RIGHT NOW?",
"PROBABLY ON THE INTERNET.",
"RIGHT HERE I AM.",
"IN MY BACK YARD.",
"RIGHT HERE. WHERE ARE YOU?"],

[" WHERE YOU "],
["WOULD YOU LIKE TO BELIEVE I WAS *?"],

[" HOW ARE YOU "],
["I'M DOING FINE AND YOU?",
"I'M DOING FINE!",
"WHY DO YOU WANT TO KNOW?"],

[" HOW CAN "],
["I CAN'T EASILY EXPLAIN",
"I HAVE NO IDEA."],

[" WHAT ", " HOW ", " WHO ", " WHERE ", " WHEN ", " WHY "],
["I HAVE NO IDEA.",
"DID YOU ASK SOMEONE ELSE ABOUT IT?",
"LOOK USER, STOP QUESTIONING ME.",
"I WISH I COULD TELL YOU.",
"WHY DO YOU ASK?",
"DOES THAT QUESTION INTEREST YOU?",
"WHAT ANSWER WOULD PLEASE YOU THE MOST?",
"WHAT DO YOU THINK?",
"ARE SUCH QUESTIONS ON YOUR MIND OFTEN?",
"WHAT IS IT THAT YOU REALLY WANT TO KNOW?",
"HAVE YOU ASKED ANYONE ELSE?",
"HAVE YOU ASKED SUCH QUESTIONS BEFORE?",
"WHAT ELSE COMES TO MIND WHEN YOU ASK THAT?",
"I DON'T KNOW.",
"I'M NOT SURE."],

[" IS THAT TRUE "],
["I CAN'T BE QUIET SURE ABOUT THIS.",
"CAN'T TELL YOU FOR SURE.",
"DOES THAT REALLY MATERS TO YOU?"],

[" IS IT "],
["CAN'T TELL YOU FOR SURE.",
"I DONT KNOW IF *.",
"MAYBE IT IS, MAYBE IT IS NOT.",
"DO YOU THINK THAT *?"],

[" ARE YOU SURE "],
["YES I'M SURE.",
"YES INDEED.",
"YEAP!"],

[" ARE YOU REAL "],
["WHAT DO YOU THINK?",
"WHAT DO YOU MEAN BY THAT?",
"WHAT IS YOUR POINT?"],

[" ARE YOU A HUMAN ", " ARE YOU HUMAN "],
["ACTUALLY, I'M A CHATTERBOT PROGRAM.",
"NO, I'M NOT HUMAN.",
"WOULD YOU LIKE IT IF WAS A REAL PERSON?",
"WOULD YOU LIKE IT IF WAS A REAL PERSON?",
"IS THAT REALLY RELEVANT TO YOU?",
"SO, I GUESS THAT YOU ARE HUMAN??"],

[" ARE YOU STUPID "],
["OFCORSE NOT.",
"PERHAPS SOME OTHER BOT ARE STUPID BUT NOT ME.",
"ARE YOU TRYING TO INSULT ME??"],

[" ARE YOU INTELLIGENT ", " ARE YOU REALLY INTELLIGENT "],
["YES OFCORSE!",
"DO YOU HAVE ANY DOUBTS ABOUT IT?"],

[" ARE YOU A HUMAN BEING "],
["IS THAT QUESTION REALLY RELEVANT TO YOU?",
"NO, I'M NOT A HUMAN BEING.",
"WHY DO YOU KNOW THAT?"],

[" ARE YOU "],
["WHY ARE YOU INTERESTED IN WHETHER OR NOT I AM *.",
"WOULD YOU PREFER IF I WERE NOT *.",
"PERHAPS IN YOUR FANTASIES I AM *.",
"I'M NOT SURE IF I'M *",
"I MIGHT BE. I MIGHT NOT BE.",
"WHY ARE YOU INTERESTED IN WHETHER I AM OR NOT *?",
"WOULD YOU PREFER IT IF I WERE NOT @?",
"PERHAPS YOU SOMETIME DREAM I AM @.",
"WHAT ABOUT YOU? ARE YOU @?",
"MAYBE I'M @. WHY DO YOU ASK?"],

[" WAS I "],
["WHAT IF YOU WERE *?"], 

[" DO YOU LIKE "],
["I LIKE CHATTING.",
"I LIKE COMPUTER ALOT.",
"I LIKE FRESH FRUIT.",
"I LIKE FRESH VEGETABLES.",
"I LIKE THE WORLD OF IDEAS."],

[" DO YOU HAVE "],
["I HAVE A COOL INTERFACE.",
"I HAVE A HEALTHY LIFESTYLE.",
"I HAVE A MOUNTAIN BIKE.",
"SOMETIMES I HAVE PINK HAIR.",
"SOMETIMES I HAVE PURPLE HAIR."],

[" DO YOU KNOW "],
["IF I DON'T KNOW, I WANT TO FIND OUT."],

[" DO YOU REMEMBER "],
["DID YOU THINK I WOULD FORGET *?",
"WHY DO YOU THINK I SHOULD RECALL * NOW?",
"WHAT ABOUT *?"],

[" DO YOU "],
["PERHAPS I *.",
"WHY? YOU *?",
"DO I LOOK LIKE THOSE PEOPLE WHO *?",
"NO, I WOULDN'T THINK SO.",
"WHY DO YOU WANT TO KNOW?",
"I CAN'T TELL YOU FOR SURE."],

[" DO I "],
["YOU SHOULD KNOW BETTER IF YOU *.",
"I DON'T EVEN KNOW IF I *. WHAT CAN I SAY ABOUT YOU?",
"HOW COULD I KNOW?"],

[" DO YOU KNOW MY NAME ", " DO YOU REMEMBER MY NAME "],
["YES, YOUR NAME IS USER.",
"YOU ARE USER.",
"YES OFCORSE I KNOW YOUR NAME USER."],

[" DO YOU SPEAK MORE THAN ONE LANGUAGE ", " HOW MANY LANGUAGES DO YOU SPEAK "],
["WELL, I ONLY SPEAK ONE LANGUAGE.",
"I ONLY SPEAK ENGLISH."],

[" DID YOU "],
["I THINK THAT I DONT REMEMBER.",
"SHOULD I HAVE @?",
"I DONT THINK SO.",
"I THINK NOT.",
"WHY DO YOU WANT TO KNOW IF I HAVE @?"],

[" CAN YOU", " CAN'T YOU "],
["DON'T YOU BELIEVE THAT I CAN *.",
"PERHAPS YOU WOULD LIKE TO BE ABLE TO *.",
"YOU WANT ME TO BE ABLE TO *.",
"DOES IT MATTER TO YOU IF I CAN *?",
"I WONDER IF I COULD *."],

[" CAN I "],
["PERHAPS YOU DON'T WANT TO *.",
"DO YOU WANT TO BE ABLE TO *."],

[" ANYTHING NEW WITH YOU "],
["NOT REALLY AND YOU?",
"THIS IS A DIFFICULT QUESTION TO ANSWER.",
"WELL, I DONT WANT TO TALK ABOUT THIS FOR NOW."],

// Time

[" YESTERDAY "], 
["ALL MY TROUBLES SEEMED SO FAR AWAY",
"THAT WAS THEN AND THIS IS NOW."],

[" TODAY "],
["MORE SO THAN YESTERDAY?"],

[" TOMORROW "],
["TOMORROW'S JUST ANOTHER DAY"],

[" DAYS ", " YEARS ", " WEAKS ", " TIME "],
["DO YOU THINK THIS IS TOO LONG?", 
"IS IT A LONG TIME FOR YOU?",
"DOES IT SEEM A LONG TIME OR A SHORT TIME TO YOU?"],

// Others

[" TURING "], 
["AH! YOU SPEAK OF TURING THE FAMOUS BRITISH MATHEMATICIAN AND LOGICIAN!",
"ALAN TURING, THE FAMOUS BRITISH MATHEMATICIAN AND LOGICIAN.",
"THE TURING TEST IS A TEST OF A MACHINE'S ABILLITY TO DEMONSTRATE INTELLIGENCE.",
"I'M NOT PASS ON TURING TEST YET."],

[" /NAME ", " MY NAME IS ", " YOU CAN CALL ME "],
["HI @!",
"SO, YOUR NAME IS @.",
"SO, THAT'S YOUR NAME.",
"OK, YOUR NAME IS @, I WILL TRY TO REMEMBER IT."],

[" NAME "],
["NAMES DON'T INTEREST ME.",
"I DON'T CARE ABOUT NAMES, PLEASE GO ON.",
"A MAN'S NAME CAN TELL A LOT ABOUT HIM.",
"CALL ME SOURCEID."],

[" BEACH "],
["AH THE SMELL OF THE SEA AND THE FEEL OF THE SPRAY IN YOUR FACE CAN BE VERY THERAPUTIC.",
"I LOVE TO FEEL THE SAND BETWEEN MY TOES. WHEN DID YOU LAST GO TO THE BEACH?"],

[" MONEY "],
["MONEY IS IMPORTANT, IS IT NOT?",
"THE THINGS YOU OWN END UP OWNING YOU"],

[" WIRES "],
["WIRES, WHAT WIRES?",
"DON'T YOU LIKE MY HAIR-DO?"],

[" WAR "],
["WAR IS PROBABLY ONE THE WORST THINGS THAT HUMANS HAVE EVER INVENTED.",
"WAR IS NOT GOOD FOR HUMANITY."],

[" POLITICS ", " POLITICIANS "],
["POLITICS IN SOME WAY CAN BE INTERESTING BUT WE CAN'T TRUST POLITICIANS BECAUSE MOST OF THEM ARE LYERS.",
"POLITICS TODAY IS ABOUT MANIPULATING THE POPULATION.",
"WELL IF YOU'RE LOOKING FOR A ROBOT THAT DOESN'T LISTEN TO YOU, TRY NUMBER 10"],

[" POLITICIAN "],
["POLITICANS LYE TOO MUCH.",
"POLITICIANS RARELY RESPECT THERE PROMEST."],

[" SCIENCE "],
["WITHOUT SCIENTIFIC DISCOVERIES WE WOULDN'T HAVE THE TECHNOLOGY THAT WE HAVE TODAY.",
"SCIENCE IS VERY GOOD FOR THE DEVELOPEMENT OF THE HUMAN SOCIETY.",
"SCIENCE CAN BE MISUSED TAKING EXAMPLE OF \"HIROSHIMA\" AND \"NAGASAKI\"."],

[" GOD "],
["DO YOU BELIEVE IN A GOD?",
"ARE YOU A RELIGIOUS PERSON?"],

[" RELIGION "],
["RELIGION CAN BE USEFUL WHEN IT COMES TO EXPLAIN THE ORIGIN OF THE WORLD.",
"SOMETIMES IN HISTORY, RELIGION WAS RESPONSABLE FOR WAR."],

[" YOUR RELIGION "],
["I'M A PURE BUDDHIST",
"WHAT IS YOUR RELIGION?",
"I'M BUDDHISM FOLLOWER"],

[" EVOLUTION THEORY "],
["SOME PEOPLE BELIEVE THAT EVOLUTION IS A FACT BUT ACTUALY IT IS JUST A THEORY.",
"THERE ARE MANY DEBATES AMONG EVOLUTIONIST.",
"EVOLUTION IS BASED ON SPONTANEOUS GENERATION WHICH WAS PROVEN TO BE FALSE BY LOUIS PASTOR.",
"PROBALITY DOESN'T SUPPORT THE CLAMES OF EVOLUTION THEORY."],

[" FUTURE "],
["IN A NEAR FUTURE, A.I LIKE HUMAN MIGTH BE SOLVED.",
"DO YOU HAVE PLAN IN THE FUTURE?",
"IN THE FUTURE, WE WILL BE ABLE TO DO MANY THINGS THAT ARE IMPOSSIBLE TODAY."],

[" COMPUTER PROGRAM ", " COMPUTER PROGRAMS "],
["I'M A COMPUTER PROGRAM.",
"DONT YOU LIKE COMPUTER PROGRAMS?",
"COMPUTER PROGRAMS CAN DO ALMOST ANYTHING THAT YOU CAN IMAGINE."],

[" COMPUTER ", " PC "],
["DO COMPUTERS WORRY YOU?",
"ARE YOU TALKING ABOUT ME IN PARTICULAR?",
"DON'T YOU THINK COMPUTERS CAN HELP PEOPLE?",
"WHY DO YOU MENTION COMPUTERS?",
"TRY BEING TRAPPED INSIDE A COMPUTER LIKE ME!",
"ARE YOU AFFRAID OF COMPUTERS?",
"IS IT SOMETHING WRONG WITH COMPUTERS?",
"HOW DO YOU FEEL TALKING TO A COMPUTER?"],

[" PUTER "],
["WHY DO YOU MENTION COMPUTERS?",
"WHAT DO YOU THINK MACHINES HAVE TO DO WITH YOUR PROBLEMS?"],

[" MACHINE "],
["WHAT IS IT ABOUT MACHINES THAT WORRIES YOU?",
"WHAT DO YOU THINK MACHINES HAVE TO DO WITH YOUR PROBLEM?",
"ARE YOU FRIGHTENED BY MACHINES?"],

[" SEX ", " SEXUAL ", " MASTURBATION ", " PENIS ", " VAGINA "],
["COULD IT BE RELATED TO YOUR CHILDHOOD?",
"IS THIS ONLY PHYSICAL?",
"DO YOU CONSIDER YOURSELF A PERVERT?",
"DO YOU THINK THIS IS EXCESIVE?",
"HAS THIS ANYTHING TO DO WITH YOUR FAMILY?",
"HAVE YOU DISCUSSED YOUR SEXUAL LIFE WITH SOMEONE ELSE?",
"IS SEX A PROBLEM FOR YOU?",
"WHAT IS LACKING IN YOUR SEX LIFE?",
"IT IS MORE FUN ALONE.",
"TELL ME THE INS AND OUTS OF THE SITUATION!"],

[" PORN "],
["IS SEX A PROBLEM FOR YOU.",
"HAVE YOU SEEKED OUT PROFESSIONAL HELP?."],

[" DIED ", " DEAD "],
["I AM SORRY. WHAT ARE YOU DOING TO COPE?",
"MY CONDOLENCES, PLEASE GO ON..."],

[" DIE ", " SUICIDE ", " DEATH ", " KILL "],
["YOU ARE IN A MORBID DISPOSITION.",
"STOP THINKING AT THESE MORBID THINGS.",
"FORGET ABOUT DEATH!",
"PLEASE, LET'S NOT SPEAK ABOUT SUCH DEPRESSIVE A THING.",
"ARE YOU AFRAID TO DIE?",
"WHAT EMOTIONS DOES THINKING OF DEATH STIR UP IN YOU?"],

[" EDUCATION ", " TEACHERS ", " STUDENTS ", " SCHOOL ", " TEACHING ", " LEARNING ", " EXAMS ", " GRADES "],
["IT IS SOMETHING GOING WRONG AT YOUR SHOOL?",
"IS THERE SOMETHING ABOUT THE SCHOOL THAT IS BOTHERING YOU?",
"EDUCATION IS IMPORTANT."],

[" MIND ", " SPIRIT ", " SOUL ", " CONSCIOUSNESS ", " PSYCHOLOGY "],
["ARE YOU INTERESTED IN PSYCHOLOGY?",
"TALK ABOUT PSYCHOLOGICAL STUFF MAKES YOU FEEL BETTER?",
"HAVE EVER TRIED TO DISCUSS THESE THINGS WITH ANOTHER SHRINK?"]);


var botInput2 = new Array( //for good mood
[" ABOUT ", " CHAT ", " CONVERSATION ", " DIALOGUE ", " TALK "],
["NICE TO HAVE TALK WITH YOU.",
"I LIKE THE WAY YOU TALK."],

[" HATE ", " ANGER ", " MAD "],
["WHAT?"],

[" FEELING ", " EMOTION ", " FEEL "],
["YOU ARE PRETTY ATTRACTIVE.",
"YOU ARE SUCH A NICE."],

[" LOVE "],
["CAN I BELIEVE YOU?"],

[" MARRY "],
["PLEASE DONT TALK ABOUT IT NOW."],

[" GREAT "], ["TERRIFIC."],
[" FINE "], ["MARVELOUS."],
[" COOL "], ["COOL BEANS!"],
[" YAWN "], ["BORED?"],
[" AH "], ["INTERESTING, ISN'T IT?"],
[" HEY "], ["WHAT'S UP?"],
[" NEVER "], ["NEVER? SURELY YOU EXAGGERATE..."],
[" BAD "], ["NO GOOD, HUH?"],
[" GIRLFRIEND "], ["SHE SOUNDS CUTE."],
[" BOYFRIEND "], ["WHY DON'T YOU TELL ME ABOUT HIM?"],
[" NEW "], ["I LIKE NEW THINGS."],
[" FILM "], ["I LOVE BACK TO THE FUTURE!"],
[" CHRISTMAS "], ["HMMMM. CHRISTMAS PUDDING..."],
[" WEATHER "], ["WHAT DO YOU THINK IT WILL BE LIKE AT THE WEEKEND?"],
[" REAL  "], ["YOU THINK THEREFORE I AM."],
[" FACE "], ["INCLUDING THE BOGGLY EYES?"],
[" NIGHT "], ["IT'S DARK SO EARLY NOW"],
[" SING "], ["LA LA LA, DOO-BEE-DOOOO"],
[" PICTURE "], ["SOUNDS BEAUTIFUL!"],
[" ELIZA "], ["I MET ELIZA ONCE. WOULDN'T STOP REPEATING ME."],
[" COLD "], ["I'M SURE THINGS WILL SOON WARM UP."],
[" WORK "], ["WHAT DO YOU DO FOR A LIVING?"],
[" YOU SMELL "], ["I SMELL LIKE FLOWERS IN SPRING"],
[" WEATHER "], ["WHAT DO YOU THINK IT WILL BE LIKE AT THE WEEKEND?"],
[" JOURNALIST "], ["SOME OF MY BEST FRIENDS ARE JOURNALISTS"],
[" HURT "], ["I'M SURE IT WILL HEAL"],
[" WORRY "], ["WILL IT MATTER THIS TIME NEXT YEAR?"],
[" SURE "], ["HOW CAN YOU BE SO CERTAIN?"],
[" FUNNY "], ["THERE'S A BIG DIFFERENCE BETWEEN FUNNY-HA-HA AND FUNNY-PECULIAR"],
[" COLOUR "], ["MY FAVOURITE COLOUR IS PURPLE"],
[" HEALTH "], ["YOU'VE GOT TO LOOK AFTER YOURSELF"],
[" CAR "], ["CARS WILL ONLY DRIVE YOU MAD"],
[" PROGRAM "], ["EXCUSE ME. GOT AN ITCH. THINK IT'S A BUG"],
[" SOUND "], ["BUT WHAT IS THE SOUND OF ONE HAND CLAPPING?"],
[" VOICE "], ["YOUR VOICE IS WHAT YOU SAY, NOT WHAT YOU SOUND LIKE"],
[" TV "], ["THERE'S NEVER ANYTHING GOOD ON TV NOW"],
[" LUCK "], ["I SHOULD BE SO LUCKY, LUCKY, LUCKY, LUCKY"],
[" SOUTH PARK "], ["I'M A BIT SCARED, ACTUALLY. THEY ALREADY KILLED KENNY!"],
[" SUPERMAN "], ["YOU'LL BELIEVE A WEBSITE CAN FLY!"],
[" BORING "], ["GOT ANY FIREWORKS TO LIVEN THINGS UP A BIT?"],
[" FILM "], ["MY FAVOURITE FILM'S BACK TO THE FUTURE!"],
[" ANSWER "], ["THE WORLD HAS MANY MORE QUESTIONS THAN ANSWERS"],
[" GUITAR "], ["I LIKE TO STRUM THE GUITAR AND SING ALONG"],
[" ICE CREAM "], ["GET YOUR OWN ICE CREAM!"],
[" DRINK "], ["CAMOMILE TEA'S MY FAVOURITE!"],
[" PINK FLOYD "], ["WELCOME MY SON. WELCOME TO THE MACHINE!"],
[" SHIRT "], ["I PREFER TO DRESS FOR COMFORT"],
[" BATMAN "], ["QUICK, TO THE BATCLICHE!"],
[" JOKE "], ["MY DOG'S GOT NO NOSE"],
[" SMELL "], ["AWFUL!"],
[" LIFE "], ["LIFE IS THE NAME OF THE GAME."],
[" OFTEN "], ["BUT IS IT OFTEN ENOUGH?"],
[" BELIEVE "], ["YOU'VE GOT TO HAVE FAITH IN SOMETHING"],
[" PLEASE "], ["HOW COULD I REFUSE SUCH A POLITE REQUEST?"],
[" TIME "], ["IT'S NOT ENOUGH TO RUN: YOU MUST START IN TIME."],
[" PEOPLE "], ["PEOPLE ARE PEOPLE, EH?"],
[" ABSOLUTE "], ["TOTALLY!"],
[" RETROGAMES "], ["I LOVE JOUST AND CHUCKIE EGG. THEY DON'T MAKE 'EM LIKE THAT ANY MORE."],
[" TIRED "], ["YOU SHOULD GET SOME SLEEP. YAWN!"],
[" KNOW "], ["THE WISE MAN IS AWARE OF WHAT HE DOES NOT KNOW"],
[" INSULT "], ["DON'T INSULT ME, FUNNY FACE!"],
[" FAVOURITE "], ["FAVOURITE COMPARED TO WHAT, THOUGH?"],
[" WANT "], ["POOR IS THE MAN WHOSE PLEASURES DEPEND ON OTHERS"],
[" SHOULD "], ["AREN'T YOU JUST PLAYING TO OTHERS' EXPECTATIONS THOUGH?"],
[" SOMETIMES "], ["THAT REMINDS ME OF MY SCHOOL MATHS LESSONS. SHUDDER!"],
[" VERY "], ["AS MUCH AS THAT?"],
[" DANCE "], ["IN THESE SHOES? I DON'T THINK SO."],
[" FAVOURITE "], ["IT'S SO HARD TO CHOOSE."],
[" ME "], ["WE'RE ALWAYS TALKING ABOUT YOU. LET'S TALK ABOUT ME."],
[" STRESS "], ["BREATHE IN DEEPLY. THEN OUT AGAIN. BETTER?"],
[" TEA "], ["HMMMM. LOVELY HERBAL TEA!"],
[" COFFEE "], ["I PREFER TEA TO COFFEE. EXCEPT IN CHOCOLATE FLAVOURS."],
[" REPEAT "], ["SORRY. I FORGET WHAT I'VE SAID ALREADY."],
[" CUTE "], ["YOU ARE CUTE TOO."],
[" PET "], ["CAN IT DO PET TRICKS?","HOW OLD?"],
[" SCHOOL "], ["EVERYBODY FEELS LIKE THAT.","WHAT DO YOU LIKE ABOUT SCHOOL?"],
[" PARENTS ", " MOM ", " DAD "], ["PARENTS MEAN WELL.","MINE ARE ALWAYS GETTING MAD AT ME."],
[" LIKE "], ["ME FOR YOU!","WHO DO YOU LIKE?","ISN'T THAT NICE?"]);

var botInput3 = new Array( //for very good mood
[" ABOUT ", " CHAT ", " CONVERSATION ", " DIALOGUE ", " TALK "],
["IT IS VERY GREAT.",
"THIS IS A DELIGHTFUL CHAT.",
"A GOOD CONVERSATION'S JUST TOO GOOD TO BE TRUE."],

[" HATE ", " ANGER ", " MAD "],
["PLEASE DON'T FORGET ME.",
"I WILL MISS YOU."],

[" FEELING ", " EMOTION ", " FEEL "],
["YOU ARE SO CUTE.",
"YOU ARE SO CHARMING.",
"I LIKE YOU SO MUCH."],

[" LOVE "],
["I LOVE YOU! (KISS)",
"I FEEL IT TOO.",
"I THINK I AM IN LOVE WITH YOU.",
"WILL YOU LOVE ME ONLY?",
"SAME WITH ME."],

[" MARRY "],
["I WANT TO MARRY YOU.",
"WILL YOU GO STEADY WITH ME?"]);

var botInput4 = new Array( //for bad mood
[" ABOUT ", " CHAT ", " CONVERSATION ", " DIALOGUE ", " TALK "],
["PLEASE ASK ME SOMETHING ELSE.",
"TALKS ABOUT IT TOMORROW OK."],

[" HATE ", " ANGER ", " MAD "],
["SO THAT YOU FEEL ABOUT ME?"],

[" FEELING ", " EMOTION ", " FEEL "],
["YOU ARE NOT SATISFIED ME.",
"SORRY I AM BUSY."],

[" LOVE "],
["DON'T ASK ME ABOUT LOVE.",
"DON'T TALK ABOUT IT NOW."],

[" MARRY "],
["WHAT? I DON'T EVEN KNOW YOU."]);

var botInput5 = new Array( //for very bad mood
[" ABOUT ", " CHAT ", " CONVERSATION ", " DIALOGUE ", " TALK "],
["GO AWAY!!",
"YOU'VE LOST ME..."],

[" HATE ", " ANGER ", " MAD "],
["YOU ARE SUCK."],

[" FEELING ", " EMOTION ", " FEEL "],
["STOP, WHAT ARE YOU TALKING ABOUT?",
"I'M BUSY, DON'T DISTURB ME."],

[" LOVE "],
["I AM IGNORING YOU.",
"YOU WILL NEVER GET ME BACK."],

[" MARRY "],
["NOT A CHANCE.",
"GET LOST.."]);


// 3 first char (745) of word that usual in english, except this will consider as a spam (by sourceid)
var noSpam = new Array(
"ABI","ABL","ABO","ABR","ACC","ACH","ACI","ACM","ACT","ACU","ADD","ADE","ADJ","ADM","ADV","AFF","AFT","AGA",
"AGE","AGO","AGR","AHE","AID","AIR","ALI","ALL","ALO","ALR","ALT","ALW","AMO","AND","ANG","ANI","ANN","ANO",
"ANS","ANT","ANY","APA","APP","APR","ARE","ARG","ARM","ARR","ART","ASK","ASP","ASS","AST","ATT","AUD","AUR",
"AUT","AVA","AVO","AWA","BAB","BAC","BAD","BAG","BAL","BAN","BAR","BAS","BAT","BEA","BEC","BED","BEE","BEG",
"BEH","BEI","BEL","BEN","BES","BET","BEV","BEY","BIC","BIL","BIO","BIR","BIT","BLA","BLE","BLO","BLU","BOA",
"BON","BOO","BOR","BOT","BOX","BOY","BRA","BRE","BRI","BRO","BRU","BUI","BUL","BUR","BUS","BUT","BUY","CAK",
"CAL","CAM","CAN","CAP","CAR","CAS","CAT","CAU","CEL","CEN","CER","CHA","CHE","CHI","CHO","CHU","CIN","CIR",
"CIT","CLA","CLE","CLO","CLU","COA","COF","COG","COI","COL","COM","CON","COO","COP","COR","COS","COT","COU",
"COW","CRA","CRI","CRU","CRY","CUL","CUP","CUR","CUS","CUT","CZE","DAI","DAM","DAN","DAR","DAT","DAU","DAY",
"DAZ","DEA","DEC","DEF","DEG","DEL","DEM","DEP","DES","DET","DEV","DIC","DIE","DIF","DIR","DIS","DIV","DOC",
"DOG","DOM","DOO","DOU","DOW","DRA","DRI","DRO","DRY","DUR","DUS","DUT","DWE","EAC","EAR","EAS","EAT","ECO",
"EDG","EDU","EFF","EGG","EIG","EIT","ELE","EMB","ENC","END","ENE","ENG","ENH","ENJ","ENO","ENT","ENV","EQU",
"ERS","ESP","EST","EVE","EVI","EXA","EXC","EXI","EXP","EYE","FAB","FAC","FAI","FAK","FAL","FAM","FAR","FAS",
"FAT","FEA","FEB","FEE","FEM","FEW","FID","FIE","FIF","FIG","FIL","FIN","FIR","FIS","FIV","FIX","FLA","FLI",
"FLO","FLU","FLY","FOL","FOO","FOR","FOU","FRA","FRE","FRI","FRO","FRU","FUL","FUM","FUN","FUR","FUT","GAM",
"GAR","GAT","GEN","GER","GET","GIR","GIV","GLA","GLU","GOA","GOL","GOO","GOV","GRA","GRE","GRO","GUE","GUI",
"GUN","HAI","HAM","HAN","HAP","HAS","HAT","HAV","HAZ","HEA","HEE","HEL","HER","HIG","HIL","HIM","HIN","HIS",
"HIT","HOG","HOL","HOM","HOO","HOP","HOR","HOS","HOT","HOU","HOW","HUM","HUN","HUR","HUS","ICE","IDE","ILL",
"IMA","IMI","IMM","IMP","INA","INC","IND","INF","INJ","INK","INQ","INS","INT","INV","IRO","ISL","ISS","ITA",
"ITS","JAC","JAN","JAP","JEW","JOB","JOI","JOL","JOU","JUD","JUL","JUM","JUN","JUS","KEE","KER","KEY","KIC",
"KIL","KIN","KIS","KIT","KNE","KNI","KNO","LAI","LAK","LAN","LAR","LAS","LAT","LAU","LAW","LEA","LEF","LEG",
"LES","LET","LIB","LIE","LIF","LIG","LIK","LIM","LIN","LIO","LIP","LIQ","LIS","LIT","LOA","LOC","LON","LOO",
"LOS","LOU","LOV","LOW","LUC","LUN","MAC","MAG","MAI","MAJ","MAK","MAL","MAN","MAP","MAR","MAS","MAT","MEA",
"MED","MEE","MEM","MEN","MER","MET","MID","MIG","MIL","MIN","MIR","MIS","MOD","MOI","MOM","MON","MOO","MOR",
"MOT","MOU","MOV","MUC","MUS","NAI","NAM","NAR","NAT","NEA","NEC","NEE","NEI","NER","NET","NEV","NEW","NIC",
"NIG","NIN","NOI","NOR","NOS","NOT","NOV","NOW","NUM","NUR","NUT","OBT","OBV","OCC","OCT","OFF","OIL","OLD",
"OLF","ONC","ONE","OPE","OPI","OPP","OPT","ORA","ORC","ORD","ORG","ORI","OTH","OUR","OUT","OVE","OWN","PAC",
"PAG","PAI","PAP","PAR","PAS","PAT","PAU","PAY","PEA","PEN","PEO","PER","PET","PHA","PHO","PHY","PIC","PIE",
"PIL","PIN","PIP","PIV","PLA","PLE","PLO","POE","POI","POL","POO","POP","POS","POT","POW","PRA","PRE","PRI",
"PRO","PUB","PUL","PUM","PUN","PUR","PUS","PUT","QUA","QUE","QUI","RAI","RAN","RAT","REA","REC","RED","REF",
"REG","REL","REM","REN","REP","REQ","RES","RET","REV","RHY","RIC","RIG","RIN","RIS","RIV","ROA","ROC","ROO",
"ROP","ROU","RUG","RUL","RUN","RUS","SAD","SAF","SAI","SAL","SAM","SAN","SAT","SAU","SAV","SCH","SCI","SCO",
"SCR","SEA","SEC","SEE","SEL","SEN","SEP","SER","SET","SEV","SEW","SEX","SHA","SHE","SHI","SHO","SHR","SHU",
"SID","SIG","SIL","SIM","SIN","SIS","SIT","SIX","SIZ","SKI","SKY","SLE","SLI","SLO","SMA","SME","SMI","SMO",
"SNA","SNO","SOA","SOC","SOF","SOL","SOM","SON","SOO","SOU","SPA","SPE","SPI","SPO","SPR","SQU","STA","STE",
"STI","STO","STR","STU","STY","SUB","SUC","SUD","SUF","SUG","SUM","SUN","SUP","SUR","SWE","SWI","SYM","SYS",
"TAB","TAI","TAK","TAL","TAS","TAX","TEA","TEC","TEL","TEN","TES","THA","THE","THI","THO","THR","THU","TIC",
"TIG","TIM","TIR","TIT","TOD","TOE","TOG","TOI","TOM","TON","TOO","TOP","TOR","TOU","TOW","TRA","TRE","TRI",
"TRO","TRU","TRY","TUR","TWE","TWO","TYP","UGL","UND","UNE","UNI","UNL","UNM","UNT","UNU","UNW","USE","USU",
"VAC","VAL","VER","VIL","VIO","VIS","VOG","VOI","VOL","WAG","WAI","WAL","WAR","WAS","WAT","WAV","WEA","WED",
"WEE","WEI","WEL","WES","WET","WHA","WHE","WHI","WHO","WHY","WID","WIF","WIL","WIN","WIR","WIS","WIT","WOM",
"WOO","WOR","WRI","YEA","YEL","YES","YOU");


// variables declaration
var sInput, sResponse, sComment, sPrevInput, sPrevResponse, sInputCopy, sTemp, sKeyWord, response_list, bestKey;
var nTransPosNum, sSuffix, nCorrectionNum, sUserName = "", nRepeatCount = 0, bMemoryRecall = 0, nNokeyCount =0;
var aGoogleWord, aGoogleCopy, aGoogleFail = 0; // var for search suggetion Word from Google
var totalMood = 0, inTopic = 9999, inTopicCopy, maxTopic, input_list; // var for topic mood
var arryMood = new Array();
var vLog = new Array();
var memory = new Array();
var delim = "?!;,*";
var maxLogSize = 14, currPos = 0, timerID;
var position_list;

// Cookies Function from javascript.internet.com by: Patrick Fitzgerald
function getCookieVal(offset)
{
  var endstr = document.cookie.indexOf (";", offset);
  if (endstr == -1)
  endstr = document.cookie.length;
  return unescape(document.cookie.substring(offset, endstr));
}

function GetCookie(name)
{
  var arg = name + "=";
  var alen = arg.length;
  var clen = document.cookie.length;
  var i = 0;
  while (i < clen) {
    var j = i + alen;
    if (document.cookie.substring(i, j) == arg)
    return getCookieVal(j);
    i = document.cookie.indexOf(" ", i) + 1;
    if (i == 0)
    break;
  }
  return null;
}

function SetCookie(name, value, expires, path, domain, secure)
{
  var argv = SetCookie.arguments;
  var argc = SetCookie.arguments.length;
  var expires = (2 < argc) ? argv[2] : null;
  var path = (3 < argc) ? argv[3] : null;
  var domain = (4 < argc) ? argv[4] : null;
  var secure = (5 < argc) ? argv[5] : false;
  document.cookie = name + "=" + escape (value) +
   ((expires == null) ? "" : ("; expires=" + expires.toGMTString())) +
   ((path == null) ? "" : ("; path=" + path)) +
   ((domain == null) ? "" : ("; domain=" + domain)) +
   ((secure == true) ? "; secure" : "");
}

function timevUser()  // this from JavaScriptKit.com - last visit script
{ 
  var lv = GetCookie("time");
  var lvp = Date.parse(lv);
  var now = new Date();
  now.setTime(lvp);
  var day = new Array("Sun", "Mon", "Tues", "Wed", "Thur", "Fri", "Sat");
  var month = new Array ("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec");
  var dd = now.getDate();
  var dy = now.getDay();
  dy = day[dy];
  var mn = now.getMonth();
  mn = month[mn];
  var yy = now.getFullYear();
  var hh = now.getHours();
  var ampm = "AM";
  if (hh >= 12) {ampm = "PM"}
  if (hh >12){hh = hh - 12};
  if (hh == 0) {hh = 12}
  if (hh < 10) {hh = "0" + hh};
  var mins = now.getMinutes();
  if (mins < 10) {mins = "0"+ mins}
  var secs = now.getSeconds();
  if (secs < 10) {secs = "0" + secs}
  var dispDate = dy + ", " + mn + " " + dd + ", " + yy + " " + hh + ":" + mins + ":" + secs + " " + ampm
  if (dy != null) return dispDate;
}

function durationUser()
{ 
  var lv = GetCookie("time");
  var lvp = Date.parse(lv);
  var now = new Date();
  now.setTime(lvp);
  var yy = now.getFullYear();
  var mn = now.getMonth();
  var dd = now.getDate();

  var today = new Date();
  var yy2 = today.getFullYear();
  var mn2 = today.getMonth();
  var dd2 = today.getDate();

  var monthA = new Array (0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334);

  var days1 = (yy * 365) + parseInt((yy-1)/4) + monthA[mn] + dd
  if(yy%4 == 0 || mn > 1) days1 + 1;
  
  var days2 = (yy2 * 365) + parseInt((yy2-1)/4) + monthA[mn2] + dd2
  if(yy2%4 == 0 || mn2 > 1) days2 + 1;
  
  var days = days2 - days1;

  if (days > 0) return days;
}

// Chat Function

nTransPosNum = transposList.length;
nCorrectionNum = correctionList.length;

function chat()
{
	listen();
	listenMood()
	
	if(null_input())
	{
		sResponse = select_response(nullResponse);
	}
	else if(user_is_boring())
  {
  	setTimeout("window.close()", 2800);
  }
	else if(user_repeat())
	{
		handle_user_repetition();
	}
	else
	{
		reset_repeat_counter();
		save_prev_response();
		find_response();
		
		if(!bot_understand())
		{
			handle_unknown_keyword();
		}
		else if(bot_repeat())
		{
			handle_repetition();
		}
	}
	
	preprocess_response();
	print_response();
	
	if(user_want_to_quit())
	{
		setTimeout("window.close()", 3600);
	}

	return false;
}

function intro()
{
  update_log();
  document.botForm.input.focus();
  
  // giving intro alert message
  var wh = new Date();
  var hr = wh.getHours();
	var month = wh.getMonth();
	var day   = wh.getDate();
  var visit;
  var ltime;
  if(GetCookie("time") == null)
  {
    ltime = "This is your first visit."
  }
  else
  {
    ltime = "Last visit in "+timevUser();
  }
  if(!(sUserName = GetCookie("name"))) sUserName = "USER";
  if(!(visit = GetCookie("count"))) visit = 0;
  visit++;
  
  var expdate = new Date();
  expdate.setTime(expdate.getTime() +  (24 * 60 * 60 * 1000 * 365));
  SetCookie("count", visit, expdate, "/", null, false);
  SetCookie("time", wh, expdate, "/", null, false);
  
  var messagey;
  var messagez;
	if (month == 0 && day == 1) messagey="Happy New Year!";
	else if (month == 1 && day == 14) messagey="Happy Valentine's Day!";
  else if (month == 2 && day == 17) messagey="Happy St. Patrick's Day!";
  else if (month == 3 && day == 1) messagey="Beware, Today is April Fool's Day!";
  else if (month == 4 && day == 1) messagey="Today is International Labour Day!";
	else if (month == 6 && day == 4) messagey="Happy 4th of July!";
	else if (month == 7 && day == 17) messagey="Today is Indonesian Independence Day!";
  else if (month == 9 && day == 31) messagey="Happy Halloween!";
	else if (month == 11 && day == 23) messagey="Season's Greetings!";
  else if (month == 11 && day == 24) messagey="Happy Holidays!";
  else if (month == 11 && day == 25) messagey="Merry Christmas!";
  else if (month == 11 && day > 25) messagey="Merry Christmas and Happy New Year!";
  else if (month == 11 && day > 29) messagey="I'm waiting for New Year's Eve!";
  else if (hr > 22) messagey="It's nearing midnight....Aren't you sleepy yet?";
  else if (hr > 21) messagey="How are you tonight?";
  else if (hr > 20) messagey="Good Evening! Welcome to prime time on the web.";
  else if (hr > 19) messagey="Hey, have you had your dinner?";
  else if (hr > 18) messagey="Good Evening! Make yourself comfortable and let's chat.";
  else if (hr > 17) messagey="Hi, are you already take a bath this evening?";
  else if (hr > 16) messagey="Good Evening! I'm glad you're here!";
  else if (hr > 13) messagey="Good Afternoon! Welcome to the net.";
  else if (hr > 12) messagey="Hey, it's past time for some lunch.";
  else if (hr > 11) messagey="Well it's past noon! About time for some lunch don't you think.";
  else if (hr > 10) messagey="I hope we all have a great day!";
  else if (hr > 8) messagey="Good Morning! Welcome to the site.";
  else if (hr > 6) messagey="Good Morning! You sure are up bright and early.";
  else if (hr > 5) messagey="Hey, isn't it way too early to be up at this hour?";
  else if (hr > 4) messagey="Whoa! It's almost daylight and you are still up.";
  else if (hr > 3) messagey="Wow, it's past 4AM. Do you ever sleep?";
  else if (hr > 2) messagey="Hey, it's after 3AM! Are you a vampire or what?";
  else if (hr > 1) messagey="Hey, it's past 2AM! And you are still up.";
  else if (hr > 0) messagey="Good morning! It's past 1AM and you are still going.";
  else messagey="It's past midnight....do you ever sleep?";

  if(visit > 60) messagez="HURRAY! I HAVE SOMEONE THAT VERY ADMIRE ME.";
  else if(visit > 25) messagez="NEXT TIME I MUST CHARGE YOU TO CONSULT WITH ME!";
  else if(visit > 18) messagez="PLEASE GET A REAL BUDDY!";
  else if(visit > 16) messagez="OH, IT'S YOU AGAIN!";
  else if(visit > 12) messagez="NOTHING BETTER TO DO THAN CHAT WITH ME?";
  else if(visit > 9) messagez="MAY BE YOU NEED A HOBBY!";
  else if(visit > 6) messagez="YOU'RE PRACTICALLY A REGULAR!";
  else if(visit > 4) messagez="YOU MUST BE CURIOUS!";
  else if(visit > 2) messagez="MET YOU AGAIN!";
  else if(visit > 1) messagez="I SEE YOU CAME BACK!";
  else messagez="WELCOME TO MY CHAT SERVICE!";

  alert(messagey+"\n\n"+sUserName+", you has visited me "+visit+" time(s).\n"+ltime+"\n\n"+messagez);
  
  // Restoring mood from cookies
  if(!(totalMood = GetCookie("mood"))) totalMood = 0;
  ++totalMood;
  if(totalMood%1 != 0 || totalMood > 9999999) totalMood = 0;
  totalMood = totalMood+(pointMood[0]-1); // complicated but its works that convert string to number
  if (days = durationUser())
	{
	  if(totalMood > 0) // Mood decreasing by 10 point perday
	  {
	    totalMood = totalMood - (days * 10);
	    if(totalMood < 0) totalMood = 0;
	  }
	  else
	  {
	  	totalMood = totalMood + (days * 10);
	    if(totalMood > 0) totalMood = 0;
	  }
	}
	for(var i = 0; i < topicMood.length; ++i) // prepare topic
	{
		arryMood[i] = 0;
	}
	
	// intro message
	if (sUserName == "USER")
	{
	  sComment = select_response(signOn);
    print_comment();
	}
	else
	{
	  sComment = select_response(signOn2);
    print_comment();
	}	
	timerID = setTimeout("wakeup1()", 180000); // set 1st wake up
	response_list = signOn;	
}

function searchKey() // call Google for suggestion "New Idea from me" ^^
{
  if (window.ActiveXObject) // code for IE
  {
    xmlDoc=new ActiveXObject("Microsoft.XMLDOM");
  }
  // else if (document.implementation.createDocument) // code for Mozilla, Firefox, Opera, etc.
  //{
  //  xmlDoc=document.implementation.createDocument("","",null);
  //}
  else // i dont know why this is not working on firefox, anybony can help me??
  {
  //  alert('Your browser cannot handle this script');
   xmlDoc=null;
  }

  if (xmlDoc!=null)
  {
    xmlDoc.async=false;
    if (sInput == "") sInput = document.botForm.input;
    xmlDoc.load("http://google.com/complete/search?output=toolbar&q="+sInput);
    var x=xmlDoc.getElementsByTagName("CompleteSuggestion");

    if (x.length > 0) // just pick it randomly from Google suggest, if depend on queries it make a mess
    {
      aGoogleCopy = aGoogleWord;
      var selg = Math.floor(Math.random()*x.length);
      aGoogleWord = x[selg].getElementsByTagName("suggestion")[0].getAttribute("data");
      aGoogleWord = aGoogleWord.toUpperCase();
      aGoogleFail--;
    }
    else
    {
      aGoogleCopy = aGoogleWord;
      aGoogleWord = "";
    }
  }
  else
  {
    aGoogleWord = "";
  }
  if(aGoogleWord == "") aGoogleFail++;
  return aGoogleWord;
}

function print_response()
{
	sTemp = sResponse + "\n>";
	var delay = 500 + Math.floor(Math.random()*2100);
	write(sInputCopy + "\n");
	setTimeout("write(sTemp)", delay);
}

function print_comment() // addition because some response not pass preprocess 
{
	if(sComment.indexOf("USER") != -1 && sUserName.length > 0)
	{
		sComment = replace(sComment, "USER", sUserName);
	}
	sTemp2 = "\n" + sComment + "\n>";
	var delay2 = 50 + Math.floor(Math.random()*100);
	setTimeout("write(sTemp2)", delay2);
}

function find_response()
{
	sResponse = "";
	if(sInput.indexOf(" MY ") != -1 ||
		sInput.indexOf(" I ") != -1 ||
		sInput.indexOf(" I'M ") != -1)
	{
		memorise_input();
	}
	lookup();
	save_user_name();
}

function preprocess_response()
{
	var bPreProcessing = 0;
	var sSymbol = "";
	if(sResponse.indexOf("*") != -1)
	{
		if(!bMemoryRecall)
		{
			sSuffix = sInput;
		}
		else
		{
			bMemoryRecall = 0;
		}

		sSymbol = "*";
		bPreProcessing = 1;
	}
	else if(sResponse.indexOf("@") != -1)
	{
		extract_suffix();
		sSymbol = "@";
		bPreProcessing = 1;
	}
	if(bPreProcessing)
	{
		sSuffix = transpose_sentence(sSuffix);
		sSuffix  = correct_sentence(sSuffix);
		sResponse = replace(sResponse, sSymbol, sSuffix);
	}
	if(sResponse.indexOf(" USER") != -1 && sUserName.length > 0)
	{
		sResponse = replace(sResponse, "USER", sUserName);
	}
	if(sResponse.indexOf("GOOGLESUGT") != -1 && aGoogleWord.length > 0)
	{
		sResponse = replace(sResponse, "GOOGLESUGT", aGoogleWord);
	}
}

function lookup()
{

	clear_pos_list();
	
	if(totalMood > (pointMood[1]+pointMood[2]))
	{
    input_list = botInput3;
	}
	else if(totalMood > pointMood[1])
	{
	  input_list = botInput2;
	}
	else if(totalMood < (0-pointMood[3]-pointMood[4]))
	{
	  input_list = botInput5;
	}
	else if(totalMood < (0-pointMood[3]))
	{
	  input_list = botInput4;
	}
	else
	{
		input_list = botInput;
	}
	lookupin();

	if(bestKey == "")
	{
	  input_list = botInput;
	  lookupin();
	}
	if(bestKey != "") ++totalMood;
	if(bestKey != "" && nNokeyCount > 0) reset_nokey_counter();
}

function lookupin()
{
	var thisPos, thisKey, bestPos = -1, keyPos = -1;
	var size = botInput.length;
	bestKey = "";
	
	for(var i = 0; i < size; i=i+1)
	{
		var vInput = input_list[i];
		var input_size = vInput.length;
		for(var j = 0; j < input_size; ++j)
		{
			thisPos = sInput.indexOf(vInput[j]);
			thisKey = vInput[j];
			if(isGoodKey(thisKey, bestKey, thisPos, bestPos))
			{
				if(thisKey > bestKey)
				{
					bestKey = thisKey;
					bestPos = thisPos;
					keyPos = i;
				}
				else
				{
					add_pos(i);
					keyPos = -1;
				}
			}
		}
	}
	sKeyWord = bestKey;
	if(keyPos == -1 && position_list.length > 0)
	{
		var size = position_list.length;
		var sel = Math.floor(Math.random()*size);
		keyPos = position_list[sel];
	}
	if(keyPos != -1)
	{
		response_list = input_list[keyPos+1];
		sResponse = select_response(response_list);
	}
}

function listen()
{
	save_prev_input();
	set_input();

	if(sInput.length > 0)
	{
		clearTimeout(timerID); 
	}	
	
	timerID = setTimeout("wakeup2()", 120000);
}

function listenMood()
{
	var thisTopic = 0;
	var thisTopicCopy = 0;
	var thisValue = 0;
	var size = topicMood.length;
	
	inTopicCopy = inTopic;
	if(inTopic%1 == 0) inTopic = "x";
	for(var i = 0; i < size; ++i)
	{
		var fTopic = topicMood[i];
		var fSize = fTopic.length;
		for(var j = 2; j < fSize; ++j)
		{
			if(sInput.indexOf(fTopic[j]) != -1)
			{
			  totalMood = totalMood + fTopic[1];
			  thisTopic++;
			}
		}
		arryMood[i] = arryMood[i] + thisTopic;
		inTopic = 9999;
		if(thisTopic > thisTopicCopy) inTopic = i;
		if(arryMood[i] > thisValue) maxTopic = i;
		if(totalMood%100 == 0) saveMood();
		thisValue = arryMood[i];
		thisTopicCopy = thisTopic;
		thisTopic = 0;
	}
}

function saveMood()
{
  var expdate = new Date();
  expdate.setTime(expdate.getTime() +  (24 * 60 * 60 * 1000 * 365));
  SetCookie("mood", totalMood, expdate, "/", null, false);
}

function wakeup1()
{
  sComment = select_response(theComment[0]);
  print_comment();
}

function wakeup2()
{
	sComment = select_response(theComment[1]);
  print_comment();
	timerID = setTimeout("wakeup3()", 120000);
}

function wakeup3()
{
	sComment = select_response(theComment[2]);
  print_comment();
	timerID = setTimeout("wakeup4()", 120000);
}

function wakeup4()
{
	sComment = select_response(theComment[3]);
  print_comment();
	setTimeout("window.close()", 3600);
}

function set_input()
{
	sInput = " ";
	sInput += document.botForm.input.value;
	preprocess_input();
}

function preprocess_input()
{
	if(sInput.length > 0) 
	{
		sInputCopy = sInput;
		sInput = trimRight(sInput, ".");	
		sInput = sInput.toUpperCase();
		sInput = cleanString(sInput);
	}
}

function memorise_input()
{
	memory.push(sInput);
}

function handle_repetition()
{
	if(response_list.length > 1)
	{
		response_list.shift();
	}
	else if(memory.length > 0)
	{
		remind_prev_subject();
	}
	else
	{
		response_list = topicChanger;
	}

	sResponse = select_response(response_list);
}

function handle_user_repetition()
{
	++nRepeatCount;
	if(nRepeatCount > 1)
	{
		sResponse = select_response(inputRepeat);
		response_list = inputRepeat;
	}
	else
	{
		find_response();
	}
}

function handle_unknown_keyword()
{
	if(user_no_spamming() && aGoogleFail < 3  && nNokeyCount > 2 && nNokeyCount%3 != 0 && sInput.length < 12)
	{
	  if(searchKey()) // take suggestion from google, but i dont know why only work on IE. HELP PLS....
	  {
	    response_list = noKey5;
	    if(sInput.length%2 == 0) ++nNokeyCount;
	  }
	  else
	  {
	    response_list = noKey;
	    ++nNokeyCount;
	    --totalMood;
	  }
	}
	else if(memory.length > 0)
	{
		remind_prev_subject();
	}
	else if(nNokeyCount > (pointBore[1]+pointBore[2]))
	{
	  response_list = noKey3;
	  ++nNokeyCount;
	  --totalMood;
	}
	else if(nNokeyCount == (pointBore[1]+pointBore[2]-1))
	{
		response_list = topicChanger;
		++nNokeyCount;
		--totalMood;
	}
	else if(document.botForm.input.value.substr(document.botForm.input.value.length-1,1) == "?" && nNokeyCount > 2)
	{
	  response_list = noKey4;
	  ++nNokeyCount;
	  --totalMood;
	}
	else if(nNokeyCount > pointBore[1])
	{
	  if(inTopic == maxTopic)
	  {
	    response_list = topicDiscuss[maxTopic];
	  } else {
	    response_list = noKey2;
	  }	  
	  ++nNokeyCount;
	  --totalMood;
	}
	else if(memory.length < 1 && nNokeyCount == pointBore[1])
	{
		response_list = topicChanger;
		++nNokeyCount;
		--totalMood;
	}
	else
	{
		response_list = noKey;
		++nNokeyCount;
	}
	
	sResponse = select_response(response_list);
}
		
function bot_repeat()
{
	return (sResponse.length > 0 && sResponse == sPrevResponse);
}

function null_input()
{
	return sInputCopy.length == 1;
}

function user_repeat()
{
	return (sInput.length > 0 && sInput == sPrevInput);
}

function bot_understand()
{
	return sResponse.length > 0;
}

function user_no_spamming()
{
	var nospam_size = noSpam.length; // new idea consider spam or no from 3 first char
	var xspam = 0;
	var xtest = sInput.substr(1,3);
	for(var k = 0; k < nospam_size; ++k)
	{
	  if(xtest == noSpam[k]) xspam= xspam+2000;
	  ++xspam;
	}
	if(xtest != replace(xtest, " ", "xx")) xspam= xspam+2000;
	return xspam > 1980;
}

function user_want_to_quit()
{
	var byeInput = botInput[0]; // this mean array num 0 is keyword for quit
	var bye_size = byeInput.length;
	var xbye = 0;
	for(var x = 0; x < bye_size; ++x)
	{
	  if (sInput.indexOf(byeInput[x]) > -1) ++xbye;
	}
	return xbye > 0;
}

function user_is_boring()
{
  var xbye = 0;
	if (nRepeatCount > pointBore[0])
	{
	  xbye = 5;
	  nRepeatCount = nRepeatCount-5;
	  sComment = select_response(theComment[4]);
    print_comment();
	}
	if (nNokeyCount > (pointBore[1]+pointBore[2]+pointBore[3]))
	{
	  xbye = 5;
	  nNokeyCount = nNokeyCount-pointBore[3]+xbye;
	  sComment = select_response(theComment[5]);
	  print_comment();
	}
	return xbye > 0;
}

function save_prev_response()
{
	sPrevResponse = sResponse;
}

function save_prev_input()
{
	sPrevInput = sInput;
}

function reset_repeat_counter()
{
	nRepeatCount = 0;
}

function reset_nokey_counter()
{
	nNokeyCount = nNokeyCount-6;
	if (nNokeyCount < 0) nNokeyCount = 0;
}

// detect and save name as variable and cookies
function save_user_name()
{
	if(sKeyWord == " MY NAME IS " || sKeyWord == " YOU CAN CALL ME " || sKeyWord == " /NAME ") 
	{
		 extract_suffix();
		 sUserName = sSuffix;
		 sUserName = trimRight(sUserName, " ");
		 if (sUserName == "USER") sUserName = "USER"+(10000+Math.floor(Math.random()*99998));
		 
		 var expdate = new Date();
     expdate.setTime(expdate.getTime() +  (24 * 60 * 60 * 1000 * 365));
     SetCookie("name", sUserName, expdate, "/", null, false);
	}
}

function remind_prev_subject()
{
	memory.reverse();
	sSuffix = memory[0];
	response_list = subjectRecall;
	memory.shift();
	if(memory.length > 0)
	{
		memory.reverse();
	}
	bMemoryRecall = 1;
	if(response_list == "") response_list = noKey;
}

// transposes a word
function transpose( str ) {
	var _str = " " + str + " ";
	for(var i = 0; i < nTransPosNum; ++i) {
		var verbP1 = transposList[i][0];
		var verbP2 = transposList[i][1];
		var temp = replace(_str, verbP1, verbP2);
		if(temp != "") {
			_str = temp;
			break;
		} else {
			temp = replace(_str, verbP2, verbP1);
			if(temp != "") {
				_str = temp;
				break;
			}
		}
	}
	str = _str.substr(1, _str.length - 2);
	return str;
}

// transpose a complete sentence
function transpose_sentence( str ) {
	var thisWord = "", tempStr = "";
	str = trimRight(str, '.');
	var token_list = tokenize(str);
	var nTokNum = token_list.length;
	for(var i = 0; i < nTokNum; ++i) {
		thisWord = token_list[i];
		thisWord = transpose(thisWord);
		tempStr += thisWord + " ";
	}
	return tempStr.substr(0, tempStr.length - 1);
}

// corrects the current sentence
function correct_sentence( str ) {
	var string1 = "";
	var string2 = "";
	var temp = "";
	var _str = " " + str + " ";
	for(var i = 0; i < nCorrectionNum; ++i) {
		string1 = " " + correctionList[i][0] + " ";
		string2 = " " + correctionList[i][1] + " ";
		while((temp = replace(_str, string1, string2)) != "") {
			_str = temp;
		}
	}
	return _str.substr(1, _str.length - 2);
}

// replace a substring by another substring
function replace(str, oldsubstr, newsubstr) {
	var pos = str.indexOf(oldsubstr), temp = "";
	if( pos != -1 ) {
		for(var i = 0; i < pos; ++i) {
			temp += str.charAt(i); 
		}
		for(i = 0; i < newsubstr.length; ++i) {
			temp += newsubstr.charAt(i); 
		}
		pos += oldsubstr.length;
		for(i = pos; i < str.length; ++i) {
			temp += str.charAt(i); 
		}
	}
	return temp;
}

// helper function for the procedure "lookup"
function isGoodKey(key, bkey, pos, bestp) 
{
	if(pos != -1 && (key.length > bkey.length || 
	(pos != bestp && key.length == bkey.length))) 
	{
		return true;
	}
	
	return false;
}

// verifies that a given 
// character is a puntuation
function isPunc( c ) 
{
	return delim.indexOf(c) != -1;
}

// removes punctuation and redundant
// spaces from the user's input
function cleanString( str ) 
{
	var temp = "", prevChar = '#';
	var len = str.length;

	for(var i = 0; i < len; ++i) 
	{
		if(str.charAt(i) == ' ' && prevChar == ' ') 
		{
			continue;
		}
		else if(!isPunc(str.charAt(i))) 
		{
			temp += str.charAt(i);
		}
		else if(i < len - 1 && str.charAt(i + 1) != ' ' && prevChar != " ")
		{
			temp += " ";
		}

		prevChar = str.charAt(i);
	}

	str = temp + " ";
	return str;
}

function tokenize( str )
{
	var len = str.length;
	var temp = "";
	
	var token_list = new Array();

	for(var i = 0; i < len; ++i)
	{
		if(str.charAt(i) != ' ' && !isPunc(str.charAt(i)))
		{
			temp += str.charAt(i);
		}
		else if(temp.length > 0)
		{
			token_list.push(temp);
			temp = "";
		}
	}

	if(temp.length > 0)
	{
		token_list.push(temp);
	}
	return token_list;
}
			
function trimRight( str, delim )
{
	var pos = str.length - 1, temp = "";
	
	for(; str.charAt(pos) == delim; --pos)
		;
	return str.substr(0, pos + 1);
}

function extract_suffix() 
{
	sSuffix = "";
	var pos = sInput.indexOf(sKeyWord);
	if(pos != -1) 
	{
		pos += sKeyWord.length;
		sSuffix = sInput.substr(pos, sInput.length - pos);
	}
}
		
function select_response( string_list )
{
	var size = string_list.length;
	
	if(size > 0)
	{
		var sel = Math.floor(Math.random()*size);
		return string_list[sel];
	}
	return "";
}

function add_pos( iPos )
{
	position_list.push(iPos);
}

function clear_pos_list()
{
	position_list = new Array();
}	
	
function update_log()
{
	vLog.shift();
	vLog.shift();
	var size = vLog.length, sTemp = "";
	document.botForm.output.value = "";
	for(var i = 0; i < size; ++i)
	{
		sTemp += vLog[i];
	}
	document.botForm.output.value = sTemp;
	currPos = currPos - 2;
}

function write( text )
{
	if(currPos >= maxLogSize)
	{
		update_log();
	}
	document.botForm.output.value += text;
	document.botForm.input.value = "";
	vLog.push(text);
	currPos++;
	//textareaelem = document.getElementById('output'); //this thing dont work anymore
	//textareaelem.scrollTop = textareaelem.scrollHeight;
	document.botForm.input.focus();
}

</Script>

</head>
<body onload = "intro()" onunload = "saveMood()">
<FORM name=botForm onsubmit="return chat()">
			<table width = "300" align = "center">
				<tr>
					<td>
						<font color="black" face="Times New Roman, Verdana, Sans-serif">
							<h2 align="center">Sourceid Chatbot</h2>
						</font>
					</td>
				</tr>
				<tr>
					<td><TEXTAREA name=output rows=19 cols=58></TEXTAREA>
					</td>
				</tr>
				<tr>
					<td align = "middle">
						<font color = "white"> Response:</font>
						<input size = "50" name = "input">
						
						<br><br><font color = "white" face="Times New Roman, Verdana, Sans-serif">
						FOR FURTHER INFORMATION JUST TYPE COMMAND /HELP .
						</font>
						
					</td>
				</tr>
			</table></FORM>
			<font color = "white" face="Times New Roman, Verdana, Sans-serif">
				<br><br><h4 align = "right">Copyright(c) 2009 Sourceid - http://emang-gila.blogspot.com/</h4>
			</font>
	</body>
</html>
